function jmenu6(val) { //직접경비
	switch (val) {
		case "1": //선불직접경비 입력 -> jejak/kb/sun.php
			return [
			
			].join('');
			
		case "3": //용지대 -> jejak/kb/exl_10.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:123px; margin-left:15px;">',
					'<div style="width:780px; height:103px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="exl_10.php">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',
										'<select name="ty" size="1" onChange="javascript:ChangeDate(17);">',
										'</select> 년&nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(17);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월&nbsp;용지대 관리 리스트</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="50" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>번호</b></span></td>',
												'<td width="400" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>거래처명</b></span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>건수</b></span></td>',
												'<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>금액</b></span></td>',
												'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>인쇄</b></span></td>',
											'</tr>',
										'</table>',
										'<table id="kbYongjiData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"><table>',
									'</td>',
								'</tr>',
						'</table>',	
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "4": //출력료 -> jejak/kb/exl_4.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:4401px; margin-left:15px;">',
					'<div style="width:780px; height:4381px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40"><span style="font-size:12pt;"><b>- &nbsp;출력료 관리 리스트</b></span></td>',
							'</tr>',					
							'<tr>',
								'<td width="780">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',                
										'<tr>',
											'<td width="140" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>지급년월일</b></span></td>',                    
											'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>거래처</b></span></td>',
											'<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>구분</b></span></td>',
											'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>금액</b></span></td>',
											'<td width="160" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>메뉴</b></span></td>',
										'</tr>',
									'</table>',
									'<table id="kbPrintData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<form name="frmMain" method="post" action="ex_4_a.php">',
										'<tr>',
											'<td width="140" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
												'<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:120px;" placeholder="2000-01-01" name="cdate"></span>',
											'</td>',
											'<td width="220" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
												'<select name="ccode" size="1">',
													'<option value="">======================</option>',
												'</select></span>',
											'</td>',
											'<td width="140" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
												'<select name="cgubn" size="1">',
													'<option value="">==========</option>',
													'<option value="표지">표지</option>',
													'<option value="본문">본문</option>',
													'<option value="칼라프린트">칼라프린트</option>',
													'<option value="스티커">스티커</option>',
													'<option value="전단지">전단지</option>',
													'<option value="프로그램">프로그램</option>',
													'<option value="포스트">포스트</option>',
												'</select></span>',
											'</td>',
											'<td width="120" height="30" align="right" style="padding-right:10" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
												'<INPUT style="text-align:right; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:110px;" name="cprice"></span>',
											'</td>',
											'<td width="160" height="30" align="center" style="padding-right:10" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
												'<input type="button" value=" 등 록 " onClick="javascript:InsertKbPrint();"></span>',
											'</td>',
										'</tr>',
										'</form>',
									'</table>',
								'</td>',
							'</tr>',
						'</table>',					
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "5": //사보료 -> jejak/kb/exl_3.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:6075px; margin-left:15px;">',
					'<div style="width:780px; height:6055px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40"><span style="font-size:12pt;"><b>- &nbsp;사보료 관리 리스트</b></span></td>',
							'</tr>',
							'<tr>',
								'<td width="780">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',                
										'<tr>',
											'<td width="140" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>지급년월일</b></span></td>',                    
											'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>거래처</b></span></td>',
											'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>구분</b></span></td>',
											'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>금액</b></span></td>',
											'<td width="200" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>메뉴</b></span></td>',
										'</tr>',
									'</table>',
									'<table id="kbHouseOrganData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>', 
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',              
										'<form name="frmMain" method="post" action="ex_3_a.php">',
										'<tr>',
											'<td width="140" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
												'<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:120px;" placeholder="2000-01-01" name="cdate"></span>',
											'</td>',
											'<td width="220" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
												'<select name="ccode" size="1">',
													'<option value="">======================</option>',
												'</select></span>',
											'</td>',
											'<td width="100" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
												'<select name="cgubn" size="1">',
													'<option value="">========</option>',
													'<option value="악보">악보</option>',
													'<option value="가사">가사</option>',
												'</select></span>',
											'</td>',
											'<td width="120" height="30" align="right" style="padding-right:10" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
												'<INPUT style="text-align:right; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:110px;" name="cprice"></span>',
											'</td>',
											'<td width="200" height="30" align="center" style="padding-right:10" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
												'<input type="button" value=" 등 록 " onClick="javascript:InsertKbHouseOrgan();"></span>',
											'</td>',
										'</tr>',
										'</form>',
									'</table>',
								'</td>',
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "6": //인쇄비 -> jejak/kb/ex_6.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:102px; margin-left:15px;">',
					'<div style="width:780px; height:82px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="ex_6.php">',
								'<tr>',
									'<td width="391" height="40"><p><span style="font-size:9pt;"><b>-&nbsp;',
										'<select name="ty" size="1" onChange="javascript:ChangeDate(18);">',
										'</select>년&nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(18);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>월&nbsp;인쇄비 관리 리스트</b></span></p>',
									'</td>',
									'<td width="391" height="40" align="right" valign="middle">',
										'<input type="button" value="거래명세 출력" onClick="javascript:ms_pr();">&nbsp;&nbsp;',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="60" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">제작번호</span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">년월일</span></td>',
												'<td width="280" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
												'<td width="77" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">거래처</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">인쇄비</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">필름.소부비</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">계산</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">회계</span></td>',
											'</tr>',
										'</table>',
										'<table id="kbPressworkData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<table id="kbPressworkData2" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td colspan="2" height="10" width="780"></td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "인쇄비_디테일":
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:1890px; margin-left:15px;">',
					'<div style="width:780px; height:1870px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
						    '<tr>',
						        '<td width="780" height="40"><span style="font-size:9pt;"><b>- &nbsp;인쇄비 관리</b></span></td>',
						    '</tr>',
						'</table>',
						'<table id="kbPressworkDetailData" border="0" cellpadding="0" cellspacing="0" width="780"></table>',   
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',   
						    '<tr>',
						        '<td width="780" height="10"></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780">',
						            '<table border="0" cellpadding="0" cellspacing="0" width="780">',
						                '<tr>',
						                    '<td width="780" height="30"><span style="font-size:9pt;">- 필름대</span></td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="780">',
						                        '<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
						                            '<tr>',
						                                '<td width="114" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">구분</span></td>',
						                                '<td width="114" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">필름량</span></td>',
						                                '<td width="114" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">필름단가</span></td>',
						                                '<td width="114" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
						                                '<td width="110" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">대지비</span></td>',
						                                '<td width="141" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">합계</span></td>',
						                                '<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수정</span></td>',
						                            '</tr>',
						                        '</table>',
						                        '<table id="kbPressworkDetailData2" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
						                    '</td>',
						                '</tr>',
						            '</table>',
						        '</td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780" height="10"></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780">',
						        	'<table border="0" cellpadding="0" cellspacing="0" width="780">',
						                '<tr>',
						                    '<td width="780" height="30"><span style="font-size:9pt;">- 소부비</span></td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="780">',
						                        '<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
						                            '<tr>',
						                                '<td width="128" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">구분</span></td>',
						                                '<td width="128" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">판종</span></td>',
						                                '<td width="128" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">판수</span></td>',
						                                '<td width="128" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">단가</span></td>',
						                                '<td width="128" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">금액</span></td>',
						                                '<td width="125" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">합계</span></td>',
						                            '</tr>',
						                        '</table>',
						                        '<table id="kbPressworkDetailData3" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
						                    '</td>',
						                '</tr>',
						            '</table>',
						        '</td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780" height="10"></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780">',
						        	'<table border="0" cellpadding="0" cellspacing="0" width="780">',
						                '<tr>',
						                    '<td width="780" height="30"><span style="font-size:9pt;">- 인쇄비</span></td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="780">',
						                    	'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
						                            '<tr>',
						                                '<td width="128" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">구분</span></td>',
						                                '<td width="128" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">R수</span></td>',
						                                '<td width="128" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">도수</span></td>',
						                                '<td width="128" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">단가</span></td>',
						                                '<td width="128" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">금액</span></td>',
						                                '<td width="125" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">합계</span></td>',
						                            '</tr>',
						                        '</table>',
						                        '<table id="kbPressworkDetailData4" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
						                    '</td>',
						                '</tr>',
						            '</table>',
						        '</td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780" height="10"></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780">',
						            '<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
						                '<tr>',
						                    '<td width="129" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>합계</b></span></td>',
						                    '<td style="padding-left:10;" width="648" bgcolor="white" height="30"><span style="font-size:9pt;"><a id="sum_all"></a></span></td>',
						                '</tr>',
						            '</table>',
						        '</td>',
						    '</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "7": //제본비 -> jejak/kb/ex_7_1.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:1890px; margin-left:15px;">',
					'<div style="width:780px; height:1870px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="ex_7_1.php">',
								'<tr>',
									'<td width="391" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',
										'<select name="ty" size="1" onChange="javascript:ChangeDate(19);">',
										'</select>년&nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(19);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>월 제본비 관리 리스트</b></span></p>',
									'</td>',
									'<td width="391" height="40" align="right" valign="middle">',
										'<input type="button" value=" 거래명세 출력 " onClick="javascript:ms_pr();">',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="60" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">제작일</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">입고일</span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">코드</span></td>',
												'<td width="260" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
												'<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">거래처</span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작부수</span></td>',
												'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제본비</span></td>',
											'</tr>',
										'</table>',
										'<table id="kbBindingData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td colspan="6" height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-left:30pt; letter-spacing:40pt;">합계</span></td>',
												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:10pt;"><a id="tsum"></a></span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "8": //코팅비 -> jejak/kb/ex_8_1.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:133px; margin-left:15px;">',
					'<div style="width:780px; height:113px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="ex_8_1.php">',
								'<tr>',
									'<td width="391" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',
										'<select name="ty" size="1" onChange="javascript:ChangeDate(20);">',
										'</select>년&nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(20);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>월&nbsp;',
										'<select name="td" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="javascript:ChangeDate(21);">',
										'</select>일&nbsp;코팅비 관리 리스트</b></span></p>',
									'</td>',
									'<td width="391" height="40" align="right" valign="middle">',
										'<input type="button" value=" 거래명세 출력 " onClick="javascript:ms_pr();">',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="60" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">제작번호</span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">년월</span></td>',
												'<td width="260" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
												'<td width="77" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">단가</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">공급가액</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">거래처</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">회계</span></td>',
											'</tr>',
										'</table>',
										'<table id="kbCoatingData1" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<table id="kbCoatingData2" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="547" height="30" colspan="5" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">합계</span></td>',
												'<td width="70" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><a id="sp3"></a></span></td>',
												'<td width="160" height="30" colspan="2" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">&nbsp;</span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td colspan="2" height="10" width="780"></td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "관리비_디테일": 
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
						    '<tr>',
						       '<td width="780" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;<a id="tag_name"></a></b></span></p></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780">',
						        	'<table id="kbManagementDetailData1" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
								'</td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780" height="10"></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780">',
						            '<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
						                '<tr>',
						                    '<td width="50" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">번호</span></td>',
						                    '<td width="80" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">년월일</span></td>',
						                    '<td width="270" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">도서명</span></td>',
						                    '<td width="70" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">단가</span></td>',
						                    '<td width="70" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">수량</span></td>',
						                    '<td width="70" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">금액</span></td>',
						                    '<td width="162" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">메뉴</span></td>',
						                '</tr>',
						            '</table>',
						            '<table id="kbManagementDetailData2" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
						            '<table id="kbManagementDetailData3" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
						            '<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<input type="hidden" name="ccode" value="<?=$cc?>">',
										'<input type="hidden" name="tag" value="<?=$tag?>">',
									'</table>',
									'<table id="kbManagementDetailData4" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
						                '<tr>',
						                    '<td width="470" align="center" valign="middle" bgcolor="#F4F4F4" height="30" colspan="4"></td>',
						                    '<td width="70" align="right" style="padding-right:10" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">합계</span></td>',
						                    '<td width="70" align="right" style="padding-right:10" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><a id="sum"></a></span></td>',
						                    '<td width="162" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"></span></td>',
						                '</tr>',
						            '</table>',
						        '</td>',
						    '</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "9": //비닐비 -> jejak/kb/exl_9.php?tag=1
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="exl_9.php">',
								'<input type="hidden" name="tag" value="<?=$tag?>">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',							
										'<select name="ty" size="1" onChange="javascript:ChangeDate(22);">',	
										'</select> 년 &nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(22);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;비닐비 관리 리스트</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="90" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>년월일</b></span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서명</b></span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서코드</b></span></td>',
												'<td width="150" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>거래처</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>수량</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>단가</b></span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>금액</b></span></td>',
											'</tr>',
										'</table>',
										'<table id="kbManagementData1" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<table id="kbManagementData2" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "10": //케이스대 -> jejak/kb/exl_9.php?tag=2
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="exl_9.php">',
								'<input type="hidden" name="tag" value="<?=$tag?>">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',							
										'<select name="ty" size="1" onChange="javascript:ChangeDate(23);">',
										'</select> 년 &nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(23);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;케이스대 관리 리스트</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="90" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>년월일</b></span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서명</b></span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서코드</b></span></td>',
												'<td width="150" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>거래처</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>수량</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>단가</b></span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>금액</b></span></td>',
											'</tr>',
										'</table>',
										'<table id="kbManagementData1" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<table id="kbManagementData2" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "11": //CD음반대 -> jejak/kb/exl_9.php?tag=3
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="exl_9.php">',
								'<input type="hidden" name="tag" value="<?=$tag?>">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',							
										'<select name="ty" size="1" onChange="javascript:ChangeDate(24);">',	
										'</select> 년 &nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(24);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;CD음반대 관리 리스트</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="90" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>년월일</b></span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서명</b></span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서코드</b></span></td>',
												'<td width="150" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>거래처</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>수량</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>단가</b></span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>금액</b></span></td>',
											'</tr>',
										'</table>',
										'<table id="kbManagementData1" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<table id="kbManagementData2" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "12": //스티커대 -> jejak/kb/exl_9.php?tag=4
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="exl_9.php">',
								'<input type="hidden" name="tag" value="<?=$tag?>">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',							
										'<select name="ty" size="1" onChange="javascript:ChangeDate(25);">',
										'</select> 년 &nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(25);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;스티커대 관리 리스트</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="90" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>년월일</b></span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서명</b></span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서코드</b></span></td>',
												'<td width="150" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>거래처</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>수량</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>단가</b></span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>금액</b></span></td>',
											'</tr>',
										'</table>',
										'<table id="kbManagementData1" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<table id="kbManagementData2" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "13": //기타 -> jejak/kb/exl_9.php?tag=5
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="exl_9.php">',
								'<input type="hidden" name="tag" value="<?=$tag?>">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',							
										'<select name="ty" size="1" onChange="javascript:ChangeDate(26);">',
										'</select> 년 &nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(26);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;기타 관리 리스트</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="90" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>년월일</b></span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서명</b></span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서코드</b></span></td>',
												'<td width="150" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>거래처</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>수량</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>단가</b></span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>금액</b></span></td>',
											'</tr>',
										'</table>',
										'<table id="kbManagementData1" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<table id="kbManagementData2" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<p><center><a href="ex_9.php?tag=5"><img src="/resources/style/images/jejak/b_in.gif" border="0"></a></center></p>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
		default:
			break;
	}
}