function jmenu4(val) { //제품제작진행
	switch (val) {
		case "0": //발주예정제품리스트 -> jejak/jj/plist.htm
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:1410px; height:100px; margin-left:15px;">',
					'<div style="width:1410px; height:80px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="1410">',
							'<form name="jeform" method="post" action="plist.htm">',
    							'<tr>',
									'<td width="1410" align="left" style="padding-left:250" valign="middle" height="40"><b><span style="font-size:12pt;">',
										'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(4);">',
										'</select>&nbsp;년&nbsp;&nbsp;',
										'<select name="tm" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(4);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>&nbsp;월&nbsp;&nbsp;',
										'<select name="td" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(5);">',
										'</select>&nbsp;&nbsp;일&nbsp;&nbsp;&nbsp;&nbsp;',
										'발 주 예 정 상 품 LIST</span><span style="font-size:11pt;">&nbsp;</span><font color="#666666"><span style="font-size:11pt;">( <a id="time_result"></a> )</span></font></b>',				
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="1410">',
										'<table id="jpBalYjData" border="0" cellpadding="5" cellspacing="0" width="1410" bgcolor="#CCCCCC"></table>',
										'<table id="pagination" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0"></table>',			
									'</td>',
    							'</tr>',
    							'<tr>',
									'<td height=40 align=left valign=middle>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
										'<span style="font-size:10pt"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
										'<input type="button" id="PopUpPrintBjlist" value=" 인쇄 ">',
									'</td>',
								'</tr>',
						'</table>',						
					'</div>',
				'</div>',
			'</div>',
			].join('');
		
		case "0_인쇄팝업": //발주예정제품리스트 인쇄
			return [
			'<div style="width:780px; height:815px;">',
				'<div style="width:780px; height:100px; margin-left:15px;">',
					'<div style="width:780px; height:80px; padding:10px 0px 10px 0px;">',
						'<table id="popdata" border="0" cellpadding="0" cellspacing="0" width="780"></table>'+
						
						
							
						
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "1": //제작계획표 -> jejak/jj/mlist.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:880px; height:171px; margin-left:15px;">',
					'<div style="width:880px; height:151px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="jeform" method="post" action="mlist.php">',
								'<tr>',
									'<td width="780" height="20"><span style="font-size:9pt;"><b>-', 
										'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(4);">',
										'</select>&nbsp;년 &nbsp;&nbsp;',
										'<select name="tm" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(4);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>&nbsp;월&nbsp;&nbsp;',
										'<select name="td" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(6);">',
										'</select>&nbsp;&nbsp;일&nbsp;&nbsp;&nbsp;제작계획표</b></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',									
										'<input type="button" value=" 인 쇄 " onClick="javascript:PrintAll(<?=$sy?>,<?=$sm?>,<?=$sd?>);">',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" height="10" align="right" valign="top"><span style="font-size:9pt;">총&nbsp;&nbsp;<?=$total_record?> 건&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;page : <?=$page?>&nbsp;/&nbsp;<?=$total_page?></span></td>',
								'</tr>',
								'<tr>',
									'<td width="780" align="left" valign="top">',
										'<table border="0" cellspacing="0" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0">',
											'<tr>',
												'<td width="780"><img src="/resources/style/images/jejak/titleimg_m_plan.gif" width="880" height="58" border="0"></td>',
											'</tr>',
											'<tr>',
												'<td width="780" height="5"></td>',
											'</tr>',
											'<tr>',
												'<td width="780" align="center" valign="middle">',
													'<!-- 표시작 -->',
													'<table border="0" cellspacing="0" width="880" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" style="border-top-width:2px; border-bottom-width:1px; border-top-color:black; border-bottom-color:black; border-top-style:solid; border-bottom-style:solid;">',
														'<tr>',
															'<td width="880" colspan="3" height="5"></td>',
														'</tr>',						
													'</table>',	
													'<table id="jpJejakplanData" border="0" cellspacing="0" width="880" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" style="border-top-width:2px; border-bottom-width:1px; border-top-color:black; border-bottom-color:black; border-top-style:solid; border-bottom-style:solid;">',
													'<table id="pagination" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0"></table>',			
													'<!-- 표 끝 -->',
												'</td>',
											'</tr>',
											'<tr>',
												'<td height="40" align="center" valign="bottom"><span style="font-size:9pt;"></span></td>',											
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
						'</table>',						
					'</div>',
				'</div>',
			'</div>',
			].join('');
		case "2": //중쇄예정제품 -> jejak/jj/jy_list.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
    						'<tr>',
								'<td width="780" height="40">',
									'<form name="dform" method="post" action="jy_list.php">',
										'<table border="0" cellpadding="0" cellspacing="0" width="780">',
											'<tr>',
												'<td width="10"></td>',
												'<td width="65">',
													'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(4);">',
													'</select>',
												'</td>',
												'<td width="20" align="left"><span style="font-size:9pt;">년</span></td>',
												'<td width="65">',
													'<select name="tm" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="javascript:ChangeDate(4);">',
														'<option value="01">01</option>',
														'<option value="02">02</option>',
														'<option value="03">03</option>',
														'<option value="04">04</option>',
														'<option value="05">05</option>',
														'<option value="06">06</option>',
														'<option value="07">07</option>',
														'<option value="08">08</option>',
														'<option value="09">09</option>',
														'<option value="10">10</option>',
														'<option value="11">11</option>',
														'<option value="12">12</option>',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">월</span></td>',
												'<td width="65"><select name="td" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="javascript:ChangeDate(7);">',
													//'<option value="<?=date("d", $row[bdate])?>"><?=date("d", $row[bdate])?></option>',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">일</span></td>',
												'<td width="155" align="left"><b><span style="font-size:9pt;"> 중 쇄 예 정 상 품</span></b></td>',
												'<td width="340" align="right">',
													'<input type="button" value=" 인 쇄 " onClick="javascript:PrintAll();">',
												'</td>',
											'</tr>',
										'</table>',
									'</form>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="780">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',                    
											'<td width="50" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">코드</span></td>',
											'<td width="200" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
											'<td width="40" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">KC</span></td>',
											'<td width="40" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">구분</span></td>',
											'<td width="40" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">판형</span></td>',
											'<td width="40" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">장형</span></td>',
											'<td width="40" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">면수</span></td>',
											'<td width="50" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">가격</span></td>',
											'<td width="55" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">부수</span></td>',
											'<td width="45" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">중쇄</span></td>',
											'<td width="45" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">인세</span></td>',
											'<td width="45" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">지불</span></td>',
											'<td width="50" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">제본</span></td>',
											'<td width="40" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">비고</span></td>',
										'</tr>',
										'<tr>',
											'<td height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=$bookcode?></span></td>',
											'<td height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-left:5pt;"><?=$bookname?></span></td>',
											'<td height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-left:0pt;"><?=$kc?></span></td>',
											'<td height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=$pgubn1?></span></td>',
											'<td height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=$tpanh?></span></td>',
											'<td height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=$tjanh?></span></td>',
											'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:10pt;"><?=$tpage?></span></td>',
											'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:10pt;"><?if (!$row[bucode]) echo(number_format($row[bprice])); else echo("&nbsp;");?></span></td>',
											'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:10pt;"><?if (!$row[bucode]) echo(number_format($row[bnum])); else echo("&nbsp;");?></span></td>',
											'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:10pt;"><?if ($pgubn2 == "제작") echo("$new_num"); else echo("&nbsp;");?></span></td>',
											'<td height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:10pt;"></span></td>',
											'<td height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:0pt;"><?=$pgubn2?></span></td>',
											'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:10pt;"></span></td>',
											'<td height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:0pt;"><?=$pgubn2?></span></td>',
											'<td height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:0pt;"><?=$jebon?></span></td>',
											'<td height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"></span></td>',
										'</tr>',
									'</table>',
								'</td>',
							'</tr>',
						'</table>',	
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "3": //발주서 -> jejak/jj/bal_list.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="jeform" method="get" action="bal_list.php">',
								'<tr>',
									'<td width="782" height="40"><span style="font-size:9pt;"><b>- ', 
										'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(4);">',
										'</select>&nbsp;년&nbsp;',
										'<select name="tm" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(4);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>&nbsp;월&nbsp;',
										'<select name="td" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(8);">',
										'</select>&nbsp;일&nbsp;&nbsp;발주서 리스트</b></span>',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="100" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">년월일</span></td>',
												'<td width="440" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">거래처</span></td>',
												'<td width="115" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">구분</span></td>',
												'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">건수</span></td>',
											'</tr>',
										'</table>',
										'<table id="jpBalData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
						'</table>',					
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "발주서_디테일": //
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
						    '<tr>',
						        '<td width="780" height="40" colspan="2" align="center"><span style="font-size:13pt;"><b>발주서</b></span></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="390" height="25"><p style="margin-left:10px;"><span style="font-size:9pt;"><b><!--<font color="#666666">date&nbsp;:&nbsp;&nbsp;</font>&nbsp;&nbsp;&nbsp;-->&nbsp;&nbsp;<font color="#666666"><a id="full_date"></a></font></b></span></p></td>',
						        '<td width="390" height="25" align="right"><p style="margin-right:10px;"><span style="font-size:9pt;"><a id="wcname"></a><font color="#666666"> </font><b><font color="#666666">&nbsp;&nbsp;귀하</font></b></span></p></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780" align="left" valign="top" colspan="2">',
						        	'<table id="jpBalDetailData1" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
						        	'<table id="jpBalDetailData2" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
						        '</td>',
						    '</tr>',
						'</table>',
						'<p>',
						'<center>',
							'<input type="button" value=" 인 쇄 " onClick="javascript:PrintIt();">',
							'<input type="button" value=" email " onClick="javascript:MailIt();">',
							//
							/*'<input type="button" value=" 인 쇄 " onClick="javascript:PrintIt2();">',
							'<input type="button" value=" email " onClick="javascript:MailIt();">',*/
						'</center>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "4": //표지작업지시서 -> jejak/jj/ji_pyo.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:138px; margin-left:15px;">',
					'<div style="width:780px; height:118px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="jeform" method="get" action="ji_pyo.php">',
								'<tr>',
									'<td width="780" height="40" colspan="2"><span style="font-size:9pt;"><b>- ', 
										'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(4);">',	
										'</select>&nbsp;년&nbsp;&nbsp;',
										'<select name="tm" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(4);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>&nbsp;월&nbsp;&nbsp;',
										'<select name="td" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(9);">',
										'</select>&nbsp;일&nbsp;&nbsp;표지작업지시서</b></span>',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="390" height="25">',
										'<p style="margin-left:10px;"><span style="font-size:9pt;"><b><font color="#666666">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;삼광사&nbsp;&nbsp;&nbsp;귀하 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a id=time_result></a></font></b></span></p>',
										'<script type="text/javascript">',
											'var d = new Date();',
											'var currentTime = d.getFullYear() + " 년 " + ( d.getMonth() + 1 ) + " 월 " + d.getDate() + " 일 ";',
											'var result = document.getElementById("time_result");',
											'result.innerHTML = currentTime;',
										'</script>',
									'</td>',
									'<td width="390" height="25" align="right" style="padding-right:1;">',
										'<input type="button" value=" Excel " onClick="javascript:Excel_All(<?=$ty?>, <?=$tm?>, <?=$td?>);">&nbsp;&nbsp;&nbsp;',
										'<input type="button" value=" 인쇄 " onClick="javascript:Print_All(<?=$ty?>, <?=$tm?>, <?=$td?>);">',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="780" align="left" valign="top" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="270" align="center" valign="middle" bgcolor="#F4F4F4" height="50" rowspan="2"><p><span style="font-size:9pt;">건명</span></p></td>',
												'<td width="50" height="50" align="center" valign="middle" bgcolor="#F4F4F4" rowspan="2"><span style="font-size:9pt;">제작<br>구분</span></td>',
												'<td width="50" height="50" align="center" valign="middle" bgcolor="#F4F4F4" rowspan="2"><span style="font-size:9pt;">부수</span></td>',
												'<td width="50" height="50" align="center" valign="middle" bgcolor="#F4F4F4" rowspan="2"><span style="font-size:9pt;">구분</span></td>',
												'<td width="180" height="25" align="center" valign="middle" bgcolor="#F4F4F4" colspan="3"><span style="font-size:9pt;">용지사용</span></td>',                    
												'<td width="30" height="50" align="center" valign="middle" bgcolor="#F4F4F4" rowspan="2"><p><span style="font-size:9pt;">색도</span></p></td>',
												'<td width="50" height="50" align="center" valign="middle" bgcolor="#F4F4F4" rowspan="2"><p><span style="font-size:9pt;">작업<br>인계처</span></p></td>',
												'<td width="80" height="50" align="center" valign="middle" bgcolor="#F4F4F4" rowspan="2"><p><span style="font-size:9pt;">정가</span></p></td>',
												'<td width="120" height="50" align="center" valign="middle" bgcolor="#F4F4F4" rowspan="2"><p><span style="font-size:9pt;">비고</span></p></td>',
											'</tr>',
											'<tr>',
												'<td width="60" height="25" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">지질</span></td>',
												'<td width="60" height="25" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">정미</span></td>',
												'<td width="60" height="25" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">여분</span></td>',
											'</tr>',
										'</table>',
										'<table id="jpPyoData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "5": //본문작업지시서 -> jejak/jj/ji_bon.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:129px; margin-left:15px;">',
					'<div style="width:780px; height:109px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="jeform" method="post" action="ji_bon.php">',
								'<tr>',
									'<td width="580" height="40"><span style="font-size:9pt;"><b>- ', 
										'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(4);">',
										'</select>&nbsp;년&nbsp;&nbsp;',
										'<select name="tm" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(4);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>&nbsp;월&nbsp;&nbsp;',
										'<select name="td" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(10);">',
										'</select>&nbsp;일&nbsp;&nbsp;&nbsp;본문 작업 지시서</b></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
										'<input type="button" value="모두 인쇄" onClick="javascript:PrintAll(<?=$ty?>,<?=$tm?>,<?=$td?>)">',
									'</td>',									
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" align="left" valign="top">',
										'<table border="0" cellspacing="1" width="784" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><p><span style="font-size:9pt;">번호</span></p></td>',
												'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작일</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
												'<td width="360" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
												'<td width="84" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">인쇄</span></td>',
												'<td width="84" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제본</span></td>',
											'</tr>',	
										'</table>',
										'<table id="jpBonData" border="0" cellspacing="1" width="784" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<table id="pagination" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0"></table>',			
									'</td>',
								'</tr>',
						'</table>',												
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "본문작업지시서_디테일": //본문작업지시서_디테일
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:129px; margin-left:15px;">',
					'<div style="width:780px; height:109px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
						    '<tr>',
						        '<td width="780" height="40" colspan="2"><span style="font-size:9pt;"><b>- 본문작업지시서</b></span></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="390" height="25"><p style="margin-left:10px;"><span style="font-size:9pt;"><b><font color="#666666">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a id="wcname2"></a>&nbsp;&nbsp;귀하 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a id="bdate"></a></font></b></span></p></td>',
						        '<td width="390" height="25" align="right">&nbsp;</td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780" align="left" valign="top" colspan="2">',
						        	'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
						                '<tr>',
						                    '<td width="90" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><p><span style="font-size:9pt;">도서명</span></p></td>',
						                    '<td width="270" height="30" align="center" valign="middle" bgcolor="white" colspan="3"><span style="font-size:9pt;"><a id="bname"></a><a id="bucode"></a></span></td>',
						                    '<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">메뉴</span></td>',
						                    '<td width="330" height="30" align="left" valign="middle" bgcolor="white">',
						                        '<p style="margin-left:10px;"><span style="font-size:9pt;"><input type="button" value=" 인 쇄 " onClick="javascript:PrintAll(<?=$uid?>);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
						                        '<input type="submit" value=" 수 정 "></span></p>',
						                    '</td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">지질</span></td>',
						                    '<td width="270" height="30" align="center" valign="middle" bgcolor="white" colspan="3"><span style="font-size:9pt;"><a id="jname_jcode"></a></span></td>',
						                    '<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">판수</span></td>',
						                    '<td width="330" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><a id="pannum5"></a></span></td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작구분</span></td>',
						                    '<td width="270" height="30" align="center" valign="middle" bgcolor="white" colspan="3"><span style="font-size:9pt;"><a id="typegubn"></a></span></td>',
						                    '<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">부수</span></td>',
						                    '<td width="330" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><a id="bnum"></a> 부</span></td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="90" height="40" align="center" valign="middle" bgcolor="#F4F4F4" rowspan="2"><span style="font-size:9pt;">구분</span></td>',
						                    '<td width="90" height="40" align="center" valign="middle" bgcolor="#F4F4F4" rowspan="2"><span style="font-size:9pt;">대수</span></td>',
						                    '<td width="180" height="20" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">용지사용</span></td>',
						                    '<td width="90" height="40" align="center" valign="middle" bgcolor="#F4F4F4" rowspan="2"><span style="font-size:9pt;">색도</span></td>',
						                    '<td width="330" height="40" align="center" valign="middle" bgcolor="#F4F4F4" rowspan="2"><span style="font-size:9pt;">비고</span></td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="90" height="20" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">정미</span></td>',
						                    '<td width="90" height="20" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">여분</span></td>',
						                '</tr>',
						            '</table>',
						            '<table id="jpBonDetailData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
						            '<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
						                '<input type="hidden" name="uids[]" value="<?=$row3[uid]?>">',
						                '<tr>',
						                    '<td width="180" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">합계</span></td>',
						                    '<td width="90" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
						                        '<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:30px;" name="SU1" value=""> R', 
						                        '<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:30px;" name="SU2" value=""></span></td>',
						                    '<td width="90" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
						                        '<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:30px;" name="SU3" value=""> R', 
						                        '<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:30px;" name="SU4" value=""></span></td>',
						                    '<td width="90" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
						                        '<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:30px;" name="SU5" value=""> R', 
						                        '<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:30px;" name="SU6" value=""></span></td>',
						                    '<td width="330" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"></span></td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="180" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">사진작업완료일시</span></td>',
						                    '<td width="180" height="30" align="center" valign="middle" bgcolor="white" colspan="2"><span style="font-size:9pt;"></span></td>',
						                    '<td width="420" height="120" align="center" valign="middle" bgcolor="white" rowspan="4" colspan="2"><textarea id="comment" cols="60" rows="10" name="comm"></textarea></td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="180" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">인쇄완료일시</span></td>',
						                    '<td width="180" height="30" align="center" valign="middle" bgcolor="white" colspan="2"><span style="font-size:9pt;"><a id="pwan"></a></span></td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="180" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">작업인계처</span></td>',
						                    '<td width="180" height="30" align="center" valign="middle" bgcolor="white" colspan="2"><span style="font-size:9pt;"><a id="wcname"></a></span></td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="180" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">인계수량</span></td>',
						                    '<td width="180" height="30" align="center" valign="middle" bgcolor="white" colspan="2">&nbsp;</td>',
						                '</tr>',
						            '</table>',
						        '</td>',
						    '</tr>',
						'</table>',								
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "6": //입고 대장 -> jejak/jj/1001.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:152px; margin-left:15px;">',
					'<div style="width:780px; height:132px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="jeform" method="get" action="1001.php">',
								'<tr>',
									'<td width="782" height="40"><span style="font-size:9pt;"><b>- ', 
										'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(4);">',
										'</select>&nbsp;년&nbsp;',
										'<select name="tm" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(4);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>&nbsp;월&nbsp;',
										'<select name="td" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(11);">',
										'</select>&nbsp;일&nbsp;&nbsp;입고 대장</b></span>',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="30" align="center" valign="middle" bgcolor="#F4F4F4" height="50"><p><span style="font-size:9pt;">번호</span></p></td>',
												'<td width="320" height="50" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
												'<td width="40" height="50" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">구분</span></td>',
												'<td width="60" height="50" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작수량</span></td>',
												'<td width="60" height="50" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작일</span></td>',
												'<td width="80" height="50" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">입고예정일</span></td>', 
												'<td width="60" height="50" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">입고일</span></td>',
												'<td width="60" height="50" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제본여부</span></td>',
												'<td width="70" height="50" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제본소</span></td>',
											'</tr>',
										'</table>',
										'<table id="jpdeaData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
						'</table>',
						'<p>',
							'<center>',
								'<input type="button" value=" 인 쇄 " onClick="javascript:PrintIt2();">',
							'</center>',
						'</p>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "8": //제작예정리스트 열람 -> jejak/jj/yejung1.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:1410px; height:1340px; margin-left:15px;">',
					'<div style="width:1410px; height:1320px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="1410">',
							'<tr>',
								'<td width="1410" align="left" style="padding-left:250" valign="middle" height="40"><b><span style="font-size:12pt;"><a id=time_result></a></span>발 주 예 정 상 품 LIST&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',					
									'<input type="button" value=" 새 로 계 산 " onClick="javascript:Cal_New();"></span></b>',
								'</td>',							
							'</tr>',
						'</table>',
						'<table id="JpYejungData" border="0" cellpadding="0" cellspacing="0" width="1410"></table>',
						'<table border="0" cellpadding="0" cellspacing="0" width="1410">',
							'<tr>',
								'<td height=40 align=left valign=middle>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:10pt"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',							
									'<input type="button" value=" 인쇄 " onClick="javascript:PrintAll();">',
								'</td>',
							'</tr>',
						'</table>',					
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "9": //제작예정리스트 등록 -> jejak/jj/master_list_tmp.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:669px; margin-left:15px;">',
					'<div style="width:780px; height:649px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="100%" height="100%">',
							'<tr>',
								'<td width="100%" height="10" bgcolor="#666666"></td>',
							'</tr>',
							'<tr>',
								'<td width="100%" align="left" valign="top" height="100%" bgcolor="#EEEEEE">',
									'<table border="0" cellpadding="0" cellspacing="0" width="770">',
										'<tr>',
											'<td width="20"></td>',
											'<td width="750" align="left" valign="top">',
												'<table border="0" cellpadding="0" cellspacing="0" width="750">',
													'<tr>',
														'<td width="750" height="70">',
															'<table border="0" cellpadding="0" cellspacing="0" width="750" background="/resources/style/images/jejak/search_m_img.gif" height="50">',
																'<tr>',
																	'<td width="20" height="50"><img src="/resources/style/images/jejak/search_l_img.gif" width="20" height="50" border="0"></td>',
																	'<form name="form1" method="post" action="master_list_tmp.php">',
																	'<td width="710" height="50" align="center" valign="middle">',
																		'<table border="0" cellpadding="0" cellspacing="0" width="565">',
																			'<tr>',
																				'<td width="50"><img src="/resources/style/images/jejak/search_txt.gif" width="45" height="20" border="0">&nbsp;&nbsp;</td>',
																				'<td width="80">',
																					'<SELECT name=keyfield style="font-family:돋움; font-size:9pt;">',
																						'<OPTION value="SBBOOK">도서코드</OPTION>',
																						'<OPTION value="SBNAME2">도서명</OPTION>',
																					'</SELECT>',
																				'</td>',
																				'<td width="370"><INPUT style="font-family:굴림; font-size:9pt; width:270px;" name=key onkeydown="javascript:Enter_Check(2);" size="23"></td>',
																				'<td width="65" align="right"><input type="button" value="검색하기" onclick="javascript:SearchBook(2);"></td>',
																			'</tr>',
																		'</table>',
																	'</td>',
																	'</form>',
																	'<td width="20" height="50"><img src="/resources/style/images/jejak/search_r_img.gif" width="20" height="50" border="0"></td>',
																'</tr>',
															'</table>',
														'</td>',
													'</tr>',												
													'<tr>',
														'<td width="750" height="30" align="center" valign="middle">',
															'<table border="0" cellpadding="0" cellspacing="0" width="730">',
																'<tr>',
																	'<td width="120">발주 예정 추가</td>',
																	'<td width="610" align="right"><p><span style="font-size:9pt;"><font face="돋움"><a id="time_result"></a>&nbsp;&nbsp; 현재 &nbsp;&nbsp;총 : <a id="total_record"></a> 종</font></span></p>',
																		'<script type="text/javascript">',
																			'var d = new Date();',
																			'var currentTime = d.getFullYear() + "/" + ( d.getMonth() + 1 ) + "/" + d.getDate() + " " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds();',
																			'var result = document.getElementById("time_result");',
																			'result.innerHTML = currentTime;',
																		'</script>',
																	'</td>',
																'</tr>',
															'</table>',
														'</td>',
													'</tr>',
													'<tr>',
														'<td width="750" height="5"></td>',
													'</tr>',
													'<tr>',
														'<td width="750" align="left" valign="top">',														
															'<table border="0" cellpadding="0" cellspacing="0" width="750" bgcolor="white">',
																'<tr>',
																	'<td width="750"><img src="/resources/style/images/jejak/body_t_img.gif" width="750" height="16" border="0"></td>',
																'</tr>',
																'<tr>',
																	'<td width="750" height="20"></td>',
																'</tr>',
																'<tr>',
																	'<td width="750" align="center" valign="top">',
																		'<table border="0" cellpadding="2" cellspacing="1" width="710" bgcolor="#8F8D74">',
																			'<tr>',
																				'<td width="140" bgcolor="#F6F4ED" height="35" align="center" valign="middle"><span style="font-size:9pt;"><font face="돋움">도서코드</font></span></td>',
																				'<td width="430" bgcolor="#F6F4ED" height="35" align="center" valign="middle"><span style="font-size:9pt;"><font face="돋움">도서명</font></span></td>',
																				'<td width="140" bgcolor="#F6F4ED" height="35" align="center" valign="middle"><span style="font-size:9pt;"><font face="돋움">메뉴</font></span></td>',
																			'</tr>',	
																		'</table>',
																		'<table id="data2" border="0" cellpadding="2" cellspacing="1" width="710" bgcolor="#8F8D74"></table>',	
																	'</td>',
																'</tr>',
																'<tr>',
																	'<td width="750" height="20"></td>',
																'</tr>',
																'<tr>',
																	'<td width="750"><img src="/resources/style/images/jejak/body_d_img.gif" width="750" height="15" border="0"></td>',
																'</tr>',
															'</table>',
														'</td>',
													'</tr>',
													'<tr>',
														'<td width="750">&nbsp;</td>',
													'</tr>',
													'<table id="pagination" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0"></table>',			
													/*'<tr>',
														'<td width="750" align="center"><span style="font-size:10pt;"><font face="돋움"></font></span></td>',						
													'</tr>',*/
												'</table>',
											'</td>',
										'</tr>',
									'</table>',
								'</td>',
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "11": //제품정가인상리스트 -> jejak/jj/107.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:1713px; margin-left:15px;">',
					'<div style="width:780px; height:1693px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="760">',
							'<tr>',
								'<td width="760" align="left" valign="middle" height="40"><b><span style="font-size:9pt;">- 제품 정가인상 리스트</span></b></td>',
							'</tr>',
							'<tr>',
								'<td width="760">',
									'<table border="0" cellspacing="1" width="760" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="50" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">번호</span></td>',
											'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
											'<td width="370" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',                    
											'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">정가</span></td>',
											'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">메뉴</span></td>',
										'</tr>',
									'</table>',
									'<table id="jpPriceupData" border="0" cellspacing="1" width="760" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="760" align="center" valign="middle" height="40"><b><span style="font-size:9pt;"></span></b></td>',
							'</tr>',
						'</table>',	
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "12": //제품보류리스트 -> jejak/jj/105.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:36340px; margin-left:15px;">',
					'<div style="width:780px; height:36320px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="760">',
							'<tr>',
								'<td width="760" align="left" valign="middle" height="40"><b><span style="font-size:9pt;">- 제품 보류 리스트</span></b></td>',
							'</tr>',
							'<tr>',
								'<td width="760">',
									'<table border="0" cellspacing="1" width="760" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="50" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">번호</span></td>',
											'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
											'<td width="370" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',                    
											'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"></span></td>',
											'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"></span></td>',
										'</tr>',
									'</table>',
									'<table id="jpholdData" border="0" cellspacing="1" width="760" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="760" align="center" valign="middle" height="40"><b><span style="font-size:9pt;">',						
									//'<input type="submit" value=" 수 정 "></input>',
								'</span></b></td>',
							'</tr>',
						'</table>',												
					'</div>',
				'</div>',
			'</div>',
			].join('');
		case "13": //제품폐간리스트 -> jejak/jj/106.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:101843px; margin-left:15px;">',
					'<div style="width:780px; height:101823px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="760">',
							'<tr>',
								'<td width="760" align="left" valign="middle" height="40"><b><span style="font-size:9pt;">- 제품 폐간 리스트</span></b></td>',
							'</tr>',
							'<tr>',
								'<td width="760">',
									'<table border="0" cellspacing="1" width="760" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="50" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">번호</span></td>',
											'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
											'<td width="370" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',                    
											'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"></span></td>',
											'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"></span></td>',
										'</tr>',
									'</table>',
									'<table id="jpCloseData" border="0" cellspacing="1" width="760" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="760" align="center" valign="middle" height="40"><b><span style="font-size:9pt;">',					
									//'<input type="submit" value=" 수 정 ">',
								'</span></b></td>',
							'</tr>',
						'</table>',				
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "14": //신간적정재고관리 -> jejak/jj/0101.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:2163px; margin-left:15px;">',
					'<div style="width:780px; height:2143px; padding:10px 0px 10px 0px;">',
						'<form name="frmMain" method="post" action="0101_m.php">',
							'<table border="0" cellpadding="0" cellspacing="0" width="760">',
								'<tr>',
									'<td width="760" align="left" valign="middle" height="40"><b><span style="font-size:9pt;">- 신간 적정재고 관리</span></b></td>',
								'</tr>',
								'<tr>',
									'<td width="760">',
										'<table border="0" cellspacing="1" width="760" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="120" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">최초발행</span></td>',
												'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
												'<td width="300" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',                    
												'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">적정재고</span></td>',
												'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">메뉴</span></td>',
											'</tr>',
										'</table>',
										'<table id="jpNewstockData" border="0" cellspacing="1" width="760" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="760" align="center" valign="middle" height="40"><b><span style="font-size:9pt;">',
										'<input type="button" value=" 수 정 " onClick="javascript:ModiJpNewstockList();">',
									'</span></b></td>',
								'</tr>',
							'</table>',
						'</form>',				
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "16": //SAMPLE제작 -> jejak/sample/list.htm
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:664px; margin-left:15px;">',
					'<div style="width:780px; height:644px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="100%" height="100%">',
							'<tr>',
								'<td width="100%" height="10" bgcolor="#666666"></td>',
							'</tr>',
							'<tr>',
								'<td width="100%" align="left" valign="top" height="100%" bgcolor="#EEEEEE">',
									'<table border="0" cellpadding="0" cellspacing="0" width="770">',
										'<tr>',
											'<td width="20"></td>',
											'<td width="750" align="left" valign="top">',
												'<table border="0" cellpadding="0" cellspacing="0" width="750">',
													'<tr>',
														'<td width="750" height="5"></td>',
													'</tr>',
													'<tr>',
														'<td width="750" align="left" valign="top">',													
															'<table border="0" cellpadding="0" cellspacing="0" width="750" bgcolor="white">',
																'<tr>',
																	'<td width="750"><img src="/resources/style/images/jejak/body_t_img.gif" width="750" height="16" border="0"></td>',
																'</tr>',
																'<tr>',
																	'<td width="750" height="40" align="right" style="padding-right:20pt;">',
																		'<input type="button" value="도서등록" onClick="javascript:BookIn();">',
																	'</td>',
																'</tr>',
																'<tr>',
																	'<td width="750" align="center" valign="top">',
																		'<table border="0" cellpadding="2" cellspacing="1" width="710" bgcolor="#8F8D74">',
																			'<tr>',
																				'<td width="80" bgcolor="#F6F4ED" height="35" align="center" valign="middle"><span style="font-size:9pt;"><font face="돋움">임시코드</font></span></td>',
																				'<td width="400" bgcolor="#F6F4ED" height="35" align="center" valign="middle"><span style="font-size:9pt;"><font face="돋움">도서명</font></span></td>',
																				'<td width="230" bgcolor="#F6F4ED" height="35" align="center" valign="middle"><span style="font-size:9pt;"><font face="돋움">메뉴</font></span></td>',
																			'</tr>',																	
																			'<tr>',
																				'<td height="30" bgcolor="white" align="center" valign="middle"><span style="font-size:9pt;"><font face="돋움" color="#666666"><?=$my_code?></font></span></td>',
																				'<td height="30" bgcolor="white" align="left" valign="middle"><p style="line-height:16px; margin-left:5px;"><span style="font-size:9pt;"><font face="돋움" color="#666666"><a href="master2.php?id=<?=$my_uid?>&f=2" class="n"><?=$my_name?></a></font></span></p></td>',																			
																				'<td height="30" bgcolor="white" align="center" valign="middle"><span style="font-size:9pt;"><font face="돋움" color="#666666">',
																					'<a href="master2.php?id=<?=$my_uid?>&f=2" class="n">수정</a>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;',
																					'<a href="javascript:DelIt(<?=$my_uid?>);" class="n">삭제</a>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;',
																					'<a href="javascript:ViewIt();" class="n">제작결과보기</a></font></span>',
																				'</td>',
																			'</tr>',
																		'</table>',
																	'</td>',
																'</tr>',
																'<tr>',
																	'<td width="750" height="20"></td>',
																'</tr>',
																'<tr>',
																	'<td width="750"><img src="/resources/style/images/jejak/body_d_img.gif" width="750" height="15" border="0"></td>',
																'</tr>',
															'</table>',
														'</td>',
													'</tr>',
													'<tr>',
														'<td width="750">&nbsp;</td>',
													'</tr>',
													'<tr>',
														'<td width="750" align="center"><span style="font-size:10pt;"><font face="돋움"></font></span></td>',
													'</tr>',
												'</table>',
											'</td>',
										'</tr>',
									'</table>',
								'</td>',
							'</tr>',
						'</table>',	
					'</div>',
				'</div>',
			'</div>',
			].join('');
		default:
			break;
	}
}