function jmenu3(val) { //용지관리
	switch (val) {
		case "0": //용지구입 -> jejak/yj/yongju2.php?flg=1
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:638px; margin-left:15px;">',
					'<div style="width:780px; height:618px; padding:10px 0px 10px 0px;">',
						'<!-- 제작 용지 주문 -->	',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40"><span style="font-size:9pt;"><b>- 용지 구입</b></span></td>',
							'</tr>',
							'<tr>',
								'<td width="780" align="left" valign="top">',
									'<table id="data9" border="0" cellspacing="1" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
								'</td>',
							'</tr>',
						'</table>',

						'<!-- 거래별 원장 -->',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="cuform" method="post" action="yongju2.php">',
								'<tr>',
									'<td width="180" height="50"><span style="font-size:9pt;"><b>- 거래별원장</b></span></td>',
									'<td width="600" height="45" valign=middle align=left>',
										'<p style="margin-left:10px;"><span style="font-size:9pt;"><b><font color="#666666">',
										'<select name="ty" size="1" onChange="javascript:ChangeDate(1);">',							
										'</select>년 &nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(1);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>월</font></b></span>',
									'</td>',
								'</tr>',
							'</form>',
							'<tr>',
								'<td width="780" align="left" valign="top" colspan="2">',
//									'<form name="cuform2" method="post" action="yong_1_a.php">',
										'<table id="data6" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">구입일</span></td>',
												'<td width="75" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">구입처</span></td>',
												'<td width="55" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">용지코드</span></td>',
												'<td width="105" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">품명</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">공장도단가</span></td>',
												'<td width="40" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">할인율</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">구입단가</span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">구매수량</span></td>',
												'<td width="75" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">세액</span></td>',
												'<td width="75" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">합계</span></td>',
											'</tr>',
											'<tr>',
												'<td colspan="7" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:0pt; letter-spacing:50;">합계</span></td>',
												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
													'<table width="100%" border="0">',
														'<tr>',
															'<td width="40%" align="right"><span style="font-size:9pt; padding-right:3pt;"><a id="sum31"></a></span></td>',
															'<td width="20%" align="center"><span style="font-size:9pt;">R</span></td>',
															'<td width="40%" align="left"><span style="font-size:9pt; padding-left:3pt;"><a id="sum32"></a></span></td>',
														'</tr>',
													'</table></span>',
												'</td>',
												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:4pt;"><a id="sum1"></a></span></td>',
												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:4pt;"><a id="sum2"></a></span></td>',
												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:4pt;"><a id="sum3"></a></span></td>',
											'</tr>',
										'</table>',
//										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
//											'<tr>',
//												'<td colspan="7" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:0pt; letter-spacing:50;">합계</span></td>',
//												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt;">',
//													'<table width="100%" border="0">',
//														'<tr>',
//															'<td width="40%" align="right"><span style="font-size:9pt; padding-right:3pt;"><a id="sum31"></a></span></td>',
//															'<td width="20%" align="center"><span style="font-size:9pt;">R</span></td>',
//															'<td width="40%" align="left"><span style="font-size:9pt; padding-left:3pt;"><a id="sum32"></a></span></td>',
//														'</tr>',
//													'</table></span>',
//												'</td>',
//												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:4pt;"><a id="sum1"></a></span></td>',
//												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:4pt;"><a id="sum2"></a></span></td>',
//												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:4pt;"><a id="sum3"></a></span></td>',
//											'</tr>',
//										'</table>',
//									'</form>',	
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="780" height="10"></td>',
							'</tr>',
						'</table>',
						'<p>',
							'<div align="center">',
								//검증필요_안쓰는 기능, buyOrderInput 만들어는 둠
								'<input type ="button" value=" 입 력 " onClick="javascript:SendIt();"></input>',
								//검증필요_안쓰는 기능
								'<!-- <input type ="button" value=" 단가 계산 " onClick="javascript:SendIt2(<?=$st?>,<?=$et?>);"></input> -->',	
							'</div>',
						'</p>',
					'</div>',
				'</div>',
			'</div>'
			].join('');
			
		case "0-구입일-popup": //구입일팝업
			return [
				'<div style="width:340px; height:300px;">',
					'<center>현 구입일 : <strong><a id="dsend"></a></strong>',
					'<p>',
					//'<form name="frm1" method="post" action="chdate_a.php" onSubmit="return chS();">',
						'<input type="hidden" name="uids" value="<?=$uids?>">변경일 : ',
						'<input type="text" size="4" id="yyy" maxlength="4" placeholder="2000">년&nbsp;&nbsp;&nbsp;',
						'<input type="text" size="2" id="mmm" maxlength="2" placeholder="01">월&nbsp;&nbsp;&nbsp;',
						'<input type="text" size="2" id="ddd" maxlength="2" placeholder="01">일',
					'<p>',
						'<input type="button" value=" 변경 " onClick="javascript:window.opener.UpPopUp(1)">',
					//'</form>',
				'</div>'
			].join('');
			
		case "0-구입처-popup": //구입처 팝업
			return [
				'<div style="width:340px; height:300px;">',
					'<center>현 구매처 : <strong><a id="wcname"></a></strong>',
					'<p>',
					//'<form name="frm1" method="post" action="chcomm_a.php" onSubmit="return chS();">',
					'<input type="hidden" name="uids" value="<?=$uids?>">',
					'변경 구매처 : <select id="comm" size="6">',
					'</select>',
					'<p>',
					'<input type="button" value=" 변경 " onClick="javascript:window.opener.UpPopUp(2)">',
					//'</form>',
				'</div>'
			].join('');
			
		case "0-용지-popup": //용지 팝업
			return [
				'<div style="width:340px; height:300px;">',
					'<center>현 용지 : <strong><a id="wjname"></a></strong> (<a id="jicode"></a>)',
					'<p>',
					//'<form name="frm1" method="post" action="chyj_a.php" onSubmit="return chS();">',
						'<input type="hidden" name="uids" value="<?=$uids?>">',
						'<input type="hidden" name="old_code" value="<?=$mrow[jicode]?>">',,
						'변경 용지 : <select id="yjyj" size="6">',
						'</select>',
						'<p>',
					'<input type="button" value=" 변경 " onClick="javascript:window.opener.UpPopUp(3)">',
					//'</form>',
				'</div>'
			].join('');
			
			
			
		case "1": //거래처별 구매 -> jejak/cu/cust_1.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:237px; margin-left:15px;">',
					'<div style="width:780px; height:217px; padding:10px 0px 10px 0px;">',
						'<form name="cuform" method="post" action="cust_1.php">',
							'<table border="0" cellpadding="0" cellspacing="0" width="780">',
								'<tr>',
									'<td width="780" height="40"><span style="font-size:12pt;"><b>- 거래처별 구매</b></span></td>',
								'</tr>',
								'<tr>',
									'<td width="780" height="45" valign=middle align=left>',
										'<p style="margin-left:10px;"><span style="font-size:9pt;"><b><font color="#666666">',
											'<select name="sy" size="1">',								
											'</select>년 &nbsp;',
											'<select name="sm" size="1">',
												'<option value="01">01</option>',
												'<option value="02">02</option>',
												'<option value="03">03</option>',
												'<option value="04">04</option>',
												'<option value="05">05</option>',
												'<option value="06">06</option>',
												'<option value="07">07</option>',
												'<option value="08">08</option>',
												'<option value="09">09</option>',
												'<option value="10">10</option>',
												'<option value="11">11</option>',
												'<option value="12">12</option>',
											'</select>월 &nbsp;',
											'<select name="sd" size="1">',
												'<option value="01">01</option>',
												'<option value="02">02</option>',
												'<option value="03">03</option>',
												'<option value="04">04</option>',
												'<option value="05">05</option>',
												'<option value="06">06</option>',
												'<option value="07">07</option>',
												'<option value="08">08</option>',
												'<option value="09">09</option>',
												'<option value="10">10</option>',
												'<option value="11">11</option>',
												'<option value="12">12</option>',
												'<option value="13">13</option>',
												'<option value="14">14</option>',
												'<option value="15">15</option>',
												'<option value="16">16</option>',
												'<option value="17">17</option>',
												'<option value="18">18</option>',
												'<option value="19">19</option>',
												'<option value="20">20</option>',
												'<option value="21">21</option>',
												'<option value="22">22</option>',
												'<option value="23">23</option>',
												'<option value="24">24</option>',
												'<option value="25">25</option>',
												'<option value="26">06</option>',
												'<option value="27">27</option>',
												'<option value="28">28</option>',
												'<option value="29">29</option>',
												'<option value="30">30</option>',
												'<option value="31">31</option>',
											'</select>일 ~ ',
											'<select name="ey" size="1">',
											'</select>년 &nbsp;',
											'<select name="em" size="1">',
												'<option value="01">01</option>',
												'<option value="02">02</option>',
												'<option value="03">03</option>',
												'<option value="04">04</option>',
												'<option value="05">05</option>',
												'<option value="06">06</option>',
												'<option value="07">07</option>',
												'<option value="08">08</option>',
												'<option value="09">09</option>',
												'<option value="10">10</option>',
												'<option value="11">11</option>',
												'<option value="12">12</option>',
											'</select>월 &nbsp',
											'<select name="ed" size="1">',
												'<option value="01">01</option>',
												'<option value="02">02</option>',
												'<option value="03">03</option>',
												'<option value="04">04</option>',
												'<option value="05">05</option>',
												'<option value="06">06</option>',
												'<option value="07">07</option>',
												'<option value="08">08</option>',
												'<option value="09">09</option>',
												'<option value="10">10</option>',
												'<option value="11">11</option>',
												'<option value="12">12</option>',
												'<option value="13">13</option>',
												'<option value="14">14</option>',
												'<option value="15">15</option>',
												'<option value="16">16</option>',
												'<option value="17">17</option>',
												'<option value="18">18</option>',
												'<option value="19">19</option>',
												'<option value="20">20</option>',
												'<option value="21">21</option>',
												'<option value="22">22</option>',
												'<option value="23">23</option>',
												'<option value="24">24</option>',
												'<option value="25">25</option>',
												'<option value="26">06</option>',
												'<option value="27">27</option>',
												'<option value="28">28</option>',
												'<option value="29">29</option>',
												'<option value="30">30</option>',
												'<option value="31">31</option>',
											'</select>일</font></b></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
										'<input type="button" value="검  색" onClick="javascript:SearchYjCu();">',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="780" align="left" valign="top" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="80" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><p><span style="font-size:9pt;">거래처코드</span></p></td>',
												'<td width="291" height="30" align="left" valign="middle" bgcolor="white" colspan="7"><span style="font-size:9pt">&nbsp;&nbsp;&nbsp;&nbsp;',
													'<select name="ccode" style="font-family:돋움; font-size:9pt; width:230px;" size="1">',
														'<option value="0" selected>===========================</option>',
													'</select></span>',
												'</td>',
											'</tr>',
										'</table>',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',											
											'<tr>',
												'<td width="50" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">번호</span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">월일</span></td>',
												'<td width="231" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">품명</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">단가</span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">공급가액</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">세액</span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">합계</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">비고</span></td>',
											'</tr>',
										'</table>',
										'<table id="data4" =border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="481" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="5"><span style="font-size:9pt;">합계</span></td>',
												'<td width="80" height="30" align="right" style="padding-right:10" valign="middle" bgcolor="white"><span style="font-size:9pt;"><a id="tprice"></a></span></td>',
												'<td width="70" height="30" align="right" style="padding-right:10" valign="middle" bgcolor="white"><span style="font-size:9pt;"><a id="ttax"></a></span></td>',
												'<td width="80" height="30" align="right" style="padding-right:10" valign="middle" bgcolor="white"><span style="font-size:9pt;"><a id="tsum"></a></span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">&nbsp;</span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
							'</table>',
						'</form>',						
					'</div>',
				'</div>',
			'</div>'
			].join('');

		case "2": //용지전표 -> jejak/yj/je_list.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:207px; margin-left:15px;">',
					'<div style="width:780px; height:187px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40"><span style="font-size:9pt;">',
									'<form name="dform" method="post" action="je_list.php">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#FFFFFF">',
											'<tr>',
												'<td width="150" height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:12pt;"><b>- 용지전표</b></span></td>',
												'<td width="530" height="30" align="left" valign="middle" bgcolor="white"><span style="padding-left:30pt; font-size:9pt;">',
													'<input name="sdate" type="number" maxlength="8" size="10" style="text-align:center;">&nbsp;&nbsp;-&nbsp;&nbsp;',
													'<input name="edate" type="number" maxlength="8" size="10" style="text-align:center;">&nbsp;&nbsp;&nbsp;&nbsp;',
													'<input type="button" value="보 기" onClick="javascript:SearchYjjp(1)"></span>',
												'</td>',
												'<td width="100" height="30" align="right" valign="middle" bgcolor="white"><span style="padding-right:10pt; font-size:9pt;">',
													'<input type="button" value="모두 인쇄" onClick="javascript:Print_All()"></span>',
												'</td>',
											'</tr>',
										'</table>',
									'</form>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="780" align="left" valign="top">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">전표번호</span></td>',
											'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">사용의뢰일</span></td>',
											'<td width="200" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
											'<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">용지</span></td>',
											'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
											'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">거래처</span></td>',
											'<td width="50" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">전표</span></td>',
										'</tr>',
									'</table>',
									'<table id="data5" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'<table id="pagination" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0"></table>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="780" height="80" align="center" valign="middle"></td>',
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>'
			].join('');
		
		case "2-전표-popup": //전표팝업
			//원본은 body에 왼쪽마진 50이지만, 테이블 왼쪽마진 42로 적용해야 같음
			return [
				'<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse; margin-left:42;" bordercolor="#111111" width="358" id="AutoNumber1">',
					'<tr>',
						'<td width="55" height="34">　</td>',
						'<td width="132" height="34" colspan="2" align="right">',
							'<p style="padding-right:40pt;"><a id="a1"></a></p>',
						'</td>',
						'<td width="82" height="34">　</td>',
						'<td width="84" height="34" align="left">',
							'<p style="padding-left:32pt;"><a id="a2"></a></p>',
						'</td>',
					'</tr>',
					'<tr>',
						'<td width="55" height="31">　</td>',
						'<td width="48" height="31">　</td>',
						'<td width="250" height="31" colspan="3" align="left">',
							'<p style="padding-left:25"><a id="b1"></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a id="b2"></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a id="b3"></a></p>',
						'</td>',
					'</tr>',
					'<tr>',
						'<td width="55" height="31">　</td>',
						'<td width="48" height="31">　</td>',
						'<td width="166" height="31" colspan="2"><a id="c1"></a></td>',
						'<td width="84" height="30" align="right">',
							'<p style="padding-right:10pt;"><a id="c2"></a></p>',
						'</td>',
					'</tr>',
					'<tr>',
						'<td width="55" height="30">　</td>',
						'<td width="48" height="30">　</td>',
						'<td width="166" height="30" colspan="2"><a id="d1"></a></td>',
						'<td width="84" height="30" align="right">',
							'<p style="padding-right:5pt;"><a id="d2"></a></p>',
						'</td>',
					'</tr>',
					'<tr>',
						'<td width="55" height="30">　</td>',
						'<td width="48" height="30">　</td>',
						'<td width="84" height="30"><a id="e1"></a></td>',
						'<td width="82" height="30">　</td>',
						'<td width="84" height="30" align="left">',
							'<p style="padding-left:3pt;"><a id="e2"></a></p>',
						'</td>',
					'</tr>',
					'<tr>',
						'<td width="55" height="34">　</td>',
						'<td width="48" height="34">　</td>',
						'<td width="166" height="34" colspan="2"><a id="f1"></a></td>',
						'<td width="84" height="30" align="right">',
							'<p style="padding-right:10pt;"><a id="f2"></a></p>',
						'</td>',
					'</tr>',
					'<tr>',
						'<td width="55" height="34">　</td>',
						'<td width="48" height="34">　</td>',
						'<td width="84" height="34">　</td>',
						'<td width="82" height="34">　</td>',
						'<td width="84" height="34">　</td>',
					'</tr>',
					'<tr>',
						'<td width="55" height="31">　</td>',
						'<td width="48" height="31">　</td>',
						'<td width="84" height="31" align="left">',
							'<span style="padding-left:5pt;"><a id="g1"></a></span>',
						'</td>',
						'<td width="82" height="31" align="center"><a id="g2"></a></td>',
						'<td width="84" height="31" align="center"><a id="g3"></a></td>',
					'</tr>',
					'<tr>',
						'<td width="55" height="32">　</td>',
						'<td width="48" height="32">　</td>',
						'<td width="250" height="32" colspan="3"><a id="h1"></a></td>',
					'</tr>',
					'<tr>',
						'<td width="55" height="50">　</td>',
						'<td width="298" height="50" colspan="4"><a id="i1"></a></td>',
					'</tr>',
					'<tr>',
						'<td width="55" height="25">　</td>',
						'<td width="298" height="25" colspan="4" align="right" valign="top">',
							'<span style="font-size:9pt;"><a id="j1"></a></span>',
						'</td>',
				    '</tr>',
				  '</table>'
			].join('');
			
		case "3": //용지등록하기 -> jejak/yj/yjang1.htm
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:937px; margin-left:15px;">',
					'<div style="width:780px; height:917px; padding:10px 0px 10px 0px;">',
						'<div align="center">',
							'<table border="0" cellpadding="0" cellspacing="0" width="780">',
								'<tr>',
									'<td width="780" height="30" align="left"><span style="font-size:12pt;"><b>- 용지등록하기</b></span></td>',
								'</tr>',
								'<tr>',
									'<td width="780" height="30" valign="top" align="right" valign="middle"><a href="javascript:RegistYongji();"><img src="/resources/style/images/jejak/btn_up.gif" width="100" height="30" border="0"></a></td>',
								'</tr>',
								'<tr>',
									'<td width="780" align="left" valign="top">',
										'<table border="0" cellspacing="1" width="784" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">용지코드</span></td>',
												'<td width="200" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">용지명</span></td>',
												'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">현재고</span></td>',
												'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">단가</span></td>',
												'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">공장도가</span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">할인율</span></td>',
												'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">메뉴</span></td>',
											'</tr>',
										'</table>',
										'<table id="data3" border="0" cellspacing="1" width="784" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
								'<table id="pagination" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0"></table>',
								'<tr>',
									'<td width="780" height="50" align="center" valign="middle"><span style="font-size:9pt;"></span></td>',
								'</tr>',
							'</table>',
						'</div>',						
					'</div>',
				'</div>',
			'</div>'
			].join('');
			
		case "3-등록":
			return [
				'<div style="width:810px; height:815px;">',
					'<div style="width:780px; height:315px; margin-left:15px;">',
						'<div style="width:780px; height:295px; padding:10px 0px 10px 0px;">',
							'<form name="form1" method="post" action="yong_in_a.php">',
							'<input type="hidden" name="ctype" value="<?=$ctype?>">',
							'<input type="hidden" name="uid" value="<?=$uid?>">',
							'<input type="hidden" name="page" value="<?=$page?>">',
							'<table border="0" cellpadding="0" cellspacing="0" width="780">',
								'<tr>',
						        	'<td width="780" height="40"><span style="font-size:9pt;"><b>- 용지 등록</b></span></td>',
						        '</tr>',
						        '<tr>',
						        	'<td width="780" align="left" valign="top">',
						        		'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
							                '<tr>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><p><span style="font-size:9pt;">코드</span></p></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="ycode"></td>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">용지명</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="yname"></td>',
							                '</tr>',
							                '<tr>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">현재고</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="yrr" value="0"></td>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">현단가</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="ydan" value="0"></td>',
							                '</tr>',
							                '<tr>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">공장도가</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="facdanga" value="0"></td>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">할인율</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="halin" value="0"></td>',
							                '</tr>',
							                '<tr>',
												'<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">입사용지</span></td>',
							                    '<td width="250" height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:9pt;">&nbsp;',
							                    	'<select name="ib" size="1">',
									                    '<option value="0">입사 아님</option>',
									                    '<option value="1">250 단위</option>',
									                    '<option value="2">100 단위</option>',
									                '</select></span>',
									            '</td>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">용지구분</span></td>',
							                    '<td width="250" height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:9pt;">&nbsp;',
								                    '<select name="wjtype" size="1">',
									                    '<option value="0">============</option>',
									                    '<option value="1">아트지</option>',
									                    '<option value="2">백상지</option>',
									                    '<option value="3">이라이트지</option>',
									                    '<option value="4">IV지</option>',
									                    '<option value="5">이프라임지</option>',
								                    '</select></span>',
								                '</td>',
							                '</tr>',
							                '<tr>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">평량</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="op1" value="0"></td>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">규격</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="op2" value="0"></td>',
							                '</tr>',
							                '<tr>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">중량</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="op3" value="0"></td>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">&nbsp;</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white">&nbsp;</td>',
							                '</tr>',
							            '</table>',
							        '</td>',
							    '</tr>',
							    '<tr>',
							        '<td width="780" height="50" align="center" valign="middle">',
							            '<table border="0" cellpadding="0" cellspacing="0" width="130">',
							                '<tr>',
							                    '<td width="65" align="center" valign="middle"><a href="javascript:InYongjiList();"><img src="/resources/style/images/jejak/btn_save.gif" width="60" height="24" border="0"></a></td>',
							                    '<td width="65" align="center" valign="middle"><div onclick="javascript:m3(this);" value="3" style="cursor: pointer;"><img src="/resources/style/images/jejak/btn_cancel.gif" width="60" height="24" border="0"></div></td>',
							                '</tr>',
							            '</table>',
							        '</td>',
							    '</tr>',
							'</table>',
							'</form>',				
						'</div>',
					'</div>',
				'</div>'
				].join('');
			
		case "3-수정":
			return [
				'<div style="width:810px; height:815px;">',
					'<div style="width:780px; height:315px; margin-left:15px;">',
						'<div style="width:780px; height:295px; padding:10px 0px 10px 0px;">',
							'<form name="form1" method="post" action="yong_in_a.php">',
							'<input type="hidden" name="ctype" value="<?=$ctype?>">',
							'<input type="hidden" name="uid" value="<?=$uid?>">',
							'<input type="hidden" name="page" value="<?=$page?>">',
							'<table border="0" cellpadding="0" cellspacing="0" width="780">',
								'<tr>',
						        	'<td width="780" height="40"><span style="font-size:9pt;"><b>- 용지 수정</b></span></td>',
						        '</tr>',
						        '<tr>',
						        	'<td width="780" align="left" valign="top">',
						        		'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
							                '<tr>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><p><span style="font-size:9pt;">코드</span></p></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="ycode"></td>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">용지명</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="yname"></td>',
							                '</tr>',
							                '<tr>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">현재고</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="yrr" value="0"></td>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">현단가</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="ydan" value="0"></td>',
							                '</tr>',
							                '<tr>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">공장도가</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="facdanga" value="0"></td>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">할인율</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="halin" value="0"></td>',
							                '</tr>',
							                '<tr>',
												'<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">입사용지</span></td>',
							                    '<td width="250" height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:9pt;">&nbsp;',
							                    	'<select name="ib" size="1">',
									                    '<option value="0">입사 아님</option>',
									                    '<option value="1">250 단위</option>',
									                    '<option value="2">100 단위</option>',
									                '</select></span>',
									            '</td>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">용지구분</span></td>',
							                    '<td width="250" height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:9pt;">&nbsp;',
								                    '<select name="wjtype" size="1">',
									                    '<option value="0">============</option>',
									                    '<option value="1">아트지</option>',
									                    '<option value="2">백상지</option>',
									                    '<option value="3">이라이트지</option>',
									                    '<option value="4">IV지</option>',
									                    '<option value="5">이프라임지</option>',
								                    '</select></span>',
								                '</td>',
							                '</tr>',
							                '<tr>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">평량</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="op1" value="0"></td>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">규격</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="op2" value="0"></td>',
							                '</tr>',
							                '<tr>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">중량</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:240px;" name="op3" value="0"></td>',
							                    '<td width="140" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">&nbsp;</span></td>',
							                    '<td width="250" height="30" align="center" valign="middle" bgcolor="white">&nbsp;</td>',
							                '</tr>',
							            '</table>',
							        '</td>',
							    '</tr>',
							    /*'<tr>',
							        '<td width="780" height="50" align="center" valign="middle">',
							            '<table border="0" cellpadding="0" cellspacing="0" width="130">',
							                '<tr>',
							                    '<td width="65" align="center" valign="middle"><input type="button" id="btn_UpIt"><img src="/resources/style/images/jejak/btn_save.gif" width="60" height="24" border="0"></td>',
							                    '<td width="65" align="center" valign="middle"><a href="javascript:history.back();"><img src="/resources/style/images/jejak/btn_cancel.gif" width="60" height="24" border="0"></a></td>',
							                '</tr>',
							            '</table>',
							        '</td>',
							    '</tr>',*/
							'</table>',
							'<div style="text-align:center; padding-top:20px;">',
								'<input type="button" id="btn_UpIt" value="등록하기">&nbsp;',
								'<input type="button" value="취소">',
							'</div>',
							'</form>',				
						'</div>',
					'</div>',
				'</div>'
				].join('');
			
		case "3-용지현재고": // -> jejak/yj/yjang.htm
			return [
				'<div style="width:810px; height:815px;">',
					'<div style="width:780px; height:624px; margin-left:15px;">',
						'<div style="width:780px; height:604px; padding:10px 0px 10px 0px;">',
							'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							    '<tr>',
							        '<td width="780" height="40"><span style="font-size:12pt;"><b><a id="wjname"></a> - ( <a id="wjcode"></a> ) 용지 현재고</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
							        	'<input type="button" value=" 인 쇄 " onClick="javascript:PrintAll();"></span>',
							        '</td>',
							    '</tr>',
							    '<tr>',
							        '<td width="780" align="left" valign="top">',
							        	'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
							                '<tr>',
							                    '<td width="90" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">월일</span></td>',
							                    '<td width="240" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">적요</span></td>',
							                    '<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">전표번호</span></td>',
							                    '<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">입고수량</span></td>',
							                    '<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">출고수량</span></td>',
							                    '<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">재고수량</span></td>',
							                    '<td width="130" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">거래처</span></td>',
							                '</tr>',
							            '</table>',
							            '<table id="data8" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
							            '<table id="pagination" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0"></table>',
							        '</td>',
								'</tr>',
							'</table>',
						'</div>',
					'</div>',
				'</div>'
				].join('');
		
		case "4": //용지장부 -> jejak/yj/0101.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:4778px; margin-left:15px;">',
					'<div style="width:780px; height:4758px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40">',
									'<form name="dform" method="get" action="0101.php">',
										'<table border="0" cellpadding="0" cellspacing="0" width="780">',
											'<tr>',
												'<td width="10"></td>',
												'<td width="65">',
													'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(2);">',
													'</select>',
												'</td>',
												'<td width="20" align="left"><span style="font-size:9pt;">년</span></td>',
												'<td width="65">',
													'<select name="tm" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="javascript:ChangeDate(2);">',
														'<option value="01">01</option>',
														'<option value="02">02</option>',
														'<option value="03">03</option>',
														'<option value="04">04</option>',
														'<option value="05">05</option>',
														'<option value="06">06</option>',
														'<option value="07">07</option>',
														'<option value="08">08</option>',
														'<option value="09">09</option>',
														'<option value="10">10</option>',
														'<option value="11">11</option>',
														'<option value="12">12</option>',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">월</span></td>',                    
												'<td width="155" align="left"><b><span style="font-size:9pt;"> 용지장부</span></b></td>',
												'<td width="195" align="center"><span style="font-size:9pt;">',
													'<select size="1" name="pgubn" onChange="javascript:ChangeDate(2);">',
														'<option value="1">용지별</option>',
														'<option value="2">구매처별</option>',
													'</select></span>',
												'</td>',
												'<td width="240" align="right">',
													'<input type="button" value=" 인 쇄 " onClick="javascript:PrintAll();">',
												'</td>',
											'</tr>',
										'</table>',
									'</form>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="780">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="50" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">사용일</span></td>',
											'<td width="330" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">적요</span></td>',
											'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">전표번호</span></td>',
											'<td width="110" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">입고수량</span></td>',
											'<td width="110" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">출고수량</span></td>',
											'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">재고수량</span></td>',
										'</tr>',
									'</table>',
									'<table id="yjjang" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
								'</td>',
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>'
			].join('');

		case "5": //월별 용지 재고 현황 -> jejak/yj/yj101.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:911px; margin-left:15px;">',
					'<div style="width:780px; height:891px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="yj101.php">',
								'<tr>',
									'<td width="390" height="40">',
										'<p><span style="font-size:9pt;"><b>-&nbsp;',
										'<select name="ty" size="1" onChange="javascript:ChangeDate(3);">',	
										'</select> 년&nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(3);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월&nbsp;용지재고현황</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle">',
										'<input type="button" value=" 인 쇄 " onClick="javascript:ms_pr();">',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="160" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">원재료</span></td>',
												'<td width="155" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">기초수량</span></td>',
												'<td width="155" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">입고수량<span></td>',
												'<td width="155" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">출고수량</span></td>',
												'<td width="155" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">기말수량</span></td>',
											'</tr>',
										'</table>',
										'<table id="data7" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<table id="data7-1" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="780" colspan="2" height="40" align="center" valign="bottom">',
										//검증필요_안쓰는 기능, newYjMonth 만들어는 둠
										'<input type="button" value=" 새로 작성 " onClick="javascript:Mk_New();">',
									'</td>',							
								'</tr>',
						'</table>',						
					'</div>',
				'</div>',
			'</div>'
			].join('');
			
		case "5-월별-popup": //팝업
			return [
				'<div style="width:804px; height:547px;">',
					'<table border="0" width="600">',
						'<tr>',
							'<td colspan="4" align="left">* <a id="jname"></a></td>',
						'</tr>',
					'</table>',
					'<table border="1" width="800" cellpadding="0" cellspacing="0" bordercolor="black">',
						'<tr>',
							'<td width="60" height="30" align="center">사용일</td>',
							'<td width="340" height="30" align="center">적요</td>',
							'<td width="80" height="30" align="center">기초수량</td>',
							'<td width="80" height="30" align="center">입고수량</td>',
							'<td width="80" height="30" align="center">출고수량</td>',
							'<td width="80" height="30" align="center">기말수량</td>',
							'<td width="80" height="30" align="center">거래처</td>',
						'</tr>',
						'<tr>',
							'<td align="center" height="25">&nbsp;</td>',
							'<td align="left" height="25"><span style="padding-left:3pt;">기초</span></td>',
							'<td align="center" height="25"><a id="iw1"></a></td>',
							'<td align="center" height="25">&nbsp;</td>',
							'<td align="center" height="25">&nbsp;</td>',
							'<td align="center" height="25">&nbsp;</td>',
							'<td align="center" height="25">&nbsp;</td>',
						'</tr>',
					'</table>',
					'<table id="popdate" border="1" width="800" cellpadding="0" cellspacing="0" bordercolor="black"></table>',
					'<table border="1" width="800" cellpadding="0" cellspacing="0" bordercolor="black">',
						'<tr>',
							'<td colspan="2" align="center" height="25" width="330">기말재고수량</td>',
							'<td align="center" height="25" width="79"><a id="s_iw1"></a></td>',
							'<td align="center" height="25" width="79"><a id="sum3"></a></td>',
							'<td align="center" height="25" width="79"><a id="sum4"></a></td>',
							'<td align="center" height="25" width="79"><a id="s_iw2"></a></td>',
							'<td align="center" height="25" width="79">&nbsp;</td>',
						'</tr>',
					'</table>',
				'</div>'
			].join('');
			
		default:
			break;
	}
}