function jmenu7(val) { //월결산자료
	switch (val) {
		case "0": //도서별 원가계산서 -> jejak/kb/ex.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:123px; margin-left:15px;">',
					'<div style="width:780px; height:103px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40">',
									'<form name="dform" method="get" action="ex.php">',
										'<table border="0" cellpadding="0" cellspacing="0" width="780">',
											'<tr>',
												'<td width="10"></td>',
												'<td width="65">',
													'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(31);">',
													'</select>',
												'</td>',
												'<td width="20" align="left"><span style="font-size:9pt;">년</span></td>',
												'<td width="65">',
													'<select name="tm" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="javascript:ChangeDate(31);">',
														'<option value="01">01</option>',
														'<option value="02">02</option>',
														'<option value="03">03</option>',
														'<option value="04">04</option>',
														'<option value="05">05</option>',
														'<option value="06">06</option>',
														'<option value="07">07</option>',
														'<option value="08">08</option>',
														'<option value="09">09</option>',
														'<option value="10">10</option>',
														'<option value="11">11</option>',
														'<option value="12">12</option>',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">월</span></td>',
												'<td width="65">',
													'<select name="td" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="javascript:ChangeDate(32);">',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">일</span></td>',
												'<td width="155" align="left"><b><span style="font-size:9pt;"> 원가 계산서</span></b></td>',
												'<td width="340" align="right">',
													'<input type="button" value="용지대 계산" onClick="javascript:CalcYJ2('+ $("select[name=ty]").val() +','+ $("select[name=tm]").val() +','+ $("select[name=td]").val() +');">&nbsp;&nbsp;&nbsp;',
													'<input type="button" id="btnBookCostStatementPrint" value="모두 인쇄">',
												'</td>',
											'</tr>',
										'</table>',
									'</form>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="780">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="60" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">제작번호</span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작일</span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
											'<td width="320" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
											'<td width="80" height="30" align="right" style="padding-right:15pt" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작부수</span></td>',
											'<td width="137" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">메뉴</span></td>',
										'</tr>',
									'</table>',
									'<table id="mcBookCostStatementData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'<table id="pagination" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0"></table>',
								'</td>',
								
								
								
								
								
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "0_인쇄팝업":
			return [
				'<center>',
				'<div id=popdata>',
				'</div>',
				'</center>',
				
				'<div id="popdata2">',
				'</div>',
					
				//'<div id="aaa"></div>',
				
			/*'<div style="width:780px; height:815px;">',
				'<div style="width:780px; height:100px; margin-left:15px;">',
					'<div style="width:780px; height:80px; padding:10px 0px 10px 0px;">',
					
					'<table border="0" id="popdata" cellpadding="20" cellspacing="1" width="620" bgcolor="#333333">',
					'<div id="Testzz"></div>',
						
					'</div>',
				'</div>',
			'</div>',*/
			].join('');		
		
		case "0_상세계산": //상세 원가계산서 -> jejak/kb/ex_view.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:123px; margin-left:15px;">',
					'<div style="width:780px; height:103px; padding:10px 0px 10px 0px;">',
					'<table id="mcBookCostStatementDetailData" border="0" cellpaddig="20" cellspacing="1" width="620" bgcolor="#333333"></table>',
					'<br>',
					'<table id="mcBookCostStatementDetailData2" border="0" cellpadding="20" cellspacing="1" width="620" bgcolor="#FFFFFF"></table>',

				'</div>',
			'</div>',
			].join('');	
		
		case "0_소부대지수정": //소부대지수정-> jejak/kb/ex_view_m1.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:123px; margin-left:15px;">',
					'<div style="width:780px; height:103px; padding:10px 0px 10px 0px;">',
						'<div id="BookCostStatementSobuModify">',
						'</div>',
					'<br>',
					'aaaaaaaaaaaaaaa',

				'</div>',
			'</div>',
			].join('');	
			
		case "1": //잡물 원가계산서 -> jejak/cu/ex_j.htm
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:123px; margin-left:15px;">',
					'<div style="width:780px; height:103px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40">',
									'<form name="dform" method="post" action="ex_j.php">',
										'<table border="0" cellpadding="0" cellspacing="0" width="780">',
											'<tr>',
												'<td width="10"></td>',
												'<td width="65">',
													'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(33);">',
													'</select>',
												'</td>',
												'<td width="20" align="left"><span style="font-size:9pt;">년</span></td>',
												'<td width="65">',
													'<select name="tm" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="javascript:ChangeDate(33);">',
														'<option value="01">01</option>',
														'<option value="02">02</option>',
														'<option value="03">03</option>',
														'<option value="04">04</option>',
														'<option value="05">05</option>',
														'<option value="06">06</option>',
														'<option value="07">07</option>',
														'<option value="08">08</option>',
														'<option value="09">09</option>',
														'<option value="10">10</option>',
														'<option value="11">11</option>',
														'<option value="12">12</option>',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">월</span></td>',
												'<td width="65">',
													'<select name="td" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="javascript:ChangeDate(34);">',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">일</span></td>',
												'<td width="155" align="left"><b><span style="font-size:9pt;">잡물 원가 계산서</span></b></td>',
												'<td width="340" align="right">',				
												'<input type="button" value="모두 인쇄" id="btnJMCostStatementPrint"></td>',
											'</tr>',
										'</table>',
									'</form>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="780">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="60" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">제작번호</span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작일</span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
											'<td width="320" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
											'<td width="80" height="30" align="right" style="padding-right:15pt" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작부수</span></td>',
											'<td width="137" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">메뉴</span></td>',
										'</tr>',
									'</table>',
									'<table id="mcJMCostStatementData" order="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'<table id="pagination" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0"></table>',
								'</td>',
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
		
		case "1_상세계산": //상세 잡물계산서 -> jejak/kb/ex_view.php
			return [
			'<center>',
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:123px; margin-left:15px;">',
					'<div style="width:780px; height:103px; padding:10px 0px 10px 0px;">',
					'<table id="mcJMCostStatementDetailData" border="0" cellpaddig="20" cellspacing="1" width="620" bgcolor="#333333">',
					'<div>',
				'</div>',
			'</div>',
			'</center>',
			].join('');	
		
		case "1_인쇄팝업": //잡물 원가계산서 모두인쇄  jejak/kb/exj_view2.php
			return [
			'<div id="popdata">',
			'</div>',
			].join('');

		case "2": //품목별 원재료명세서(월별) -> jejak/kb/yj_ms.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:194px; margin-left:15px;">',
					'<div style="width:780px; height:174px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="yj_ms.php">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>-&nbsp;',
										'<select name="ty" size="1" onChange="javascript:ChangeDate(35);">',
										'</select> 년 &nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(35);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;원재료 명세서</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle">',
										'<input type="button" id="btnPumPerPrint1"  value=" 인 쇄 " >',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="80" align="center" valign="middle" bgcolor="#F4F4F4" height="60" rowspan="2"><span style="font-size:9pt;">원재료</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">기초재고</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">입고</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">출고</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">기말재고</span></td>',
											'</tr>',
											'<tr>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
											'</tr>',
										'</table>',
										'<table id="mcPumMonData1" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<table id="mcPumMonData2" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="780" colspan="2" height="40" align="center" valign="bottom">',
										'<input type="button" value="새로 작성" onclick="javascript:ChangeDate(37);">',
									'</td>',								
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "2_품목원재료월별새로작성":
			return [
			'<div id="mcPumMonInsert">',
			'</div>',
			].join('');	
			
		case "2_인쇄팝업":
			return [
			'<div style="width:780px; height:815px;">',
				'<div style="width:780px; height:100px; margin-left:15px;">',
					'<div style="width:780px; height:80px; padding:10px 0px 10px 0px;">',
						'<table id="popdata" border="0" cellpadding="0" cellspacing="0" width="780"></table>',
							
						
						'</div>',
				'</div>',
			'</div>',
			].join('');	
		
		case "3": //품목별 원재료명세서(기간) -> jejak/kb/yj_ms3.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:194px; margin-left:15px;">',
					'<div style="width:780px; height:174px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="yj_ms3.php">',
								'<tr>',
									'<td width="590" height="40"><p><span style="font-size:9pt;"><b>-&nbsp;',
										'<select name="ty" size="1" onChange="javascript:ChangeDate(36);">',
										'</select> 년&nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(36);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월&nbsp;~&nbsp;',           
										'<select name="tm2" size="1" onChange="javascript:ChangeDate(36);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;원재료 명세서</b></span></p>',
									'</td>',
									'<td width="190" height="40" align="right" valign="middle">',
										'<input type="button" id="btnPumPerPrint" value=" 인 쇄 ">',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="80" align="center" valign="middle" bgcolor="#F4F4F4" height="60" rowspan="2"><span style="font-size:9pt;">원재료</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">기초재고</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">입고</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">출고</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">기말재고</span></td>',
											'</tr>',
											'<tr>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
											'</tr>',
										'</table>',
										'<table id="mcPumPerData1" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr style="display:none;" id="in<?=$ii?>">',
												'<td width="780" bgcolor="#FFF5F5" colspan="9" align="center" valign="middle" bgcolor="white">',
													'<table width="520" border="0" cellpadding="0" cellspacing="0">',
														'<tr>',
															'<td width="520" colspan="4" height="5"></td>',
														'</tr>',
														'<tr>',
															'<td width="80" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">일자</span></td>',
															'<td width="240" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA; border-left: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">구매처</span></td>',
															'<td width="100" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA; border-left: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">수량</span></td>',
															'<td width="100" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA; border-left: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">금액</span></td>',
														'</tr>',
														'<tr>',
															'<td width="80" height="15" align="center"><span style="font-size:8pt;"><?=date("y. m. d",$crow[date])?></span></td>',
															'<td width="240" height="15" align="left"><span style="font-size:8pt; padding-left:3pt; letter-spacing:2pt;"><?=$custname?></span></td>',
															'<td width="100" height="15" align="center">',
																'<table border="0" width="100" cellpadding="0" cellspacing="0">',
																	'<tr>',
																		'<td width="70" align="right"><span style="font-size:8pt; padding-right:3pt;"><?=$tnum1?></span></td>',
																		'<td width="30" align="left"><span style="font-size:8pt; padding-left:0pt;"><?=$tnum2?></span></td>',
																	'</tr>',
																'</table>',
															'</td>',
															'<td width="100" height="15" align="right"><span style="font-size:8pt; padding-right:10pt;"><?=number_format($crow[tprice])?></span></td>',
														'</tr>',
														'<tr>',
															'<td width="320" colspan="2" height="15" align="center"><span style="font-size:8pt; letter-spacing:13pt;"><입고합계></span></td>',
															'<td width="100" height="15" align="center">',
																'<table border="0" width="100" cellpadding="0" cellspacing="0">',
																	'<tr>',
																		'<td width="70" align="right"><span style="font-size:8pt; padding-right:3pt;"><?=$tnum1?></span></td>',
																		'<td width="30" align="left"><span style="font-size:8pt; padding-left:0pt;"><?=$tnum2?></span></td>',
																	'</tr>',
																'</table></td>',
															'<td width="100" height="15" align="right"><span style="font-size:8pt; padding-right:10pt;"><?=number_format($tsum2)?></span></td>',
														'</tr>',
														'<tr>',
															'<td width="520" colspan="4" height="5"></td>',
														'</tr>',	
													'</table>',
												'</td>',
											'</tr>',
											'<tr style="display:none;" id="out<?=$ii?>">',
												'<td width="780" bgcolor="#F5F5FF" colspan="9" align="center" valign="middle" bgcolor="white">',
													'<table width="520" border="0" cellpadding="0" cellspacing="0">',
														'<tr>',
															'<td width="520" colspan="4" height="5"></td>',
														'</tr>',
														'<tr>',
															'<td width="80" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">일자</span></td>',
															'<td width="240" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA; border-left: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">출고내역</span></td>',
															'<td width="100" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA; border-left: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">수량</span></td>',
															'<td width="100" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA; border-left: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">금액</span></td>',
														'</tr>',
														'<tr>',
															'<td width="80" height="15" align="center"><span style="font-size:8pt;"><?=date("y. m. d",$crow[date])?></span></td>',
															'<td width="240" height="15" align="left"><span style="font-size:8pt; padding-left:3pt;"><?=$crow[comment]?></span></td>',
															'<td width="100" height="15" align="center">',
																'<table border="0" width="100" cellpadding="0" cellspacing="0">',
																	'<tr>',
																		'<td width="70" align="right"><span style="font-size:8pt; padding-right:3pt;"><?=$tnum1?></span></td>',
																		'<td width="30" align="left"><span style="font-size:8pt; padding-left:0pt;"><?=$tnum2?></span></td>',
																	'</tr>',
																'</table>',
															'</td>',
															'<td width="100" height="15" align="right"><span style="font-size:8pt; padding-right:10pt;"><?=number_format($crow[tprice])?></span></td>',
														'</tr>',
														'<tr>',
															'<td width="320" colspan="2" height="15" align="center"><span style="font-size:8pt; letter-spacing:13pt;"><출고합계></span></td>',
															'<td width="100" height="15" align="center">',
																'<table border="0" width="100" cellpadding="0" cellspacing="0">',
																	'<tr>',
																		'<td width="70" align="right"><span style="font-size:8pt; padding-right:3pt;"><?=$tnum1?></span></td>',
																		'<td width="30" align="left"><span style="font-size:8pt; padding-left:0pt;"><?=$tnum2?></span></td>',
																	'</tr>',
																'</table>',
															'</td>',
															'<td width="100" height="15" align="right"><span style="font-size:8pt; padding-right:10pt;"><?=number_format($tsum2)?></span></td>',
														'</tr>',
														'<tr>',
															'<td width="520" colspan="4" height="5"></td>',
														'</tr>',	
													'</table>',
												'</td>',
											'</tr>',
										'</table>',
										'<table id="mcPumPerData2" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="780" colspan="2" height="40" align="center" valign="bottom">',
										'<input type="button" value=" 새로 작성 " onClick="javascript:ChangeDate(38);">',
									'</td>',	
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "3_인쇄팝업":
			return [
			'<div style="width:780px; height:815px;">',
				'<div style="width:780px; height:100px; margin-left:15px;">',
					'<div style="width:780px; height:80px; padding:10px 0px 10px 0px;">',
						'<table id="popdata" border="0" cellpadding="0" cellspacing="0" width="780"></table>',
							
						
						'</div>',
				'</div>',
			'</div>',
			].join('');

		case "4": //제조비명세표 -> jejak/kb/new_jejo.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:960px; height:213px; margin-left:15px;">',
					'<div style="width:960px; height:193px; padding:10px 0px 10px 0px;">',
						'<div style="width:780px; height:30px; display:table-cell; vertical-align:middle; font-size:13pt;"><b>- 제조비명세표</b></div>',
						
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "5": //거래처별 지불명세서 -> jejak/kb/jejo2.php
			return [
				'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:123px; margin-left:15px;">',
					'<div style="width:780px; height:103px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40">',
									'<form name="dform" method="post" action="jejo2.php">',
										'<table border="0" cellpadding="0" cellspacing="0" width="780">',
											'<tr>',
												'<td width="10"></td>',
												'<td width="65">',
													'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="javascript:ChangeDate(50);">',
													'</select>',
												'</td>',
												'<td width="20" align="left"><span style="font-size:9pt;">년</span></td>',
												'<td width="65">',
													'<select name="tm" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="javascript:ChangeDate(50);">',
														'<option value="01">01</option>',
														'<option value="02">02</option>',
														'<option value="03">03</option>',
														'<option value="04">04</option>',
														'<option value="05">05</option>',
														'<option value="06">06</option>',
														'<option value="07">07</option>',
														'<option value="08">08</option>',
														'<option value="09">09</option>',
														'<option value="10">10</option>',
														'<option value="11">11</option>',
														'<option value="12">12</option>',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">월</span></td>',
												'<td width="155" align="left"><b><span style="font-size:9pt;">거래처별 지불명세서</span></b></td>',
												'<td width="340" align="right">',				
												'<input type="button" value="모두 인쇄" id="btnJMCostStatementPrint"></td>',
											'</tr>',
										'</table>',
									'</form>',
								'</td>',
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "6": //저자료 지급내역(상/하) -> jejak/kb/inse.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:112px; margin-left:15px;">',
					'<div style="width:780px; height:102px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="inse.php">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>-&nbsp;',
										'<select name="ty" size="1" onChange="ChangeDate(30);">',	
										'</select> 년도&nbsp;',
										'<select name="gubn" size="1" onChange="ChangeDate(30);">',
											'<option value="1">국내</option>',
											'<option value="2">해외</option>',
										'</select>&nbsp;&nbsp;',
										'<select name="gubn2" size="1" onChange="ChangeDate(30);">',
											'<option value="1">상반기</option>',
											'<option value="2">하반기</option>',
										'</select>&nbsp;&nbsp;저자료 지급 내역</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle">',
										'<input type="button" id="btnPumPerPrint" value=" 인 쇄 ">&nbsp;',
										'<input type="button" value=" EXCEL " onClick="javascript:Exc();">&nbsp;',
										'<input type="button" value=" 지출결의서 " onClick="javascript:btnRoyaltyUDER();">',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="40" align="center" valign="middle" bgcolor="#F4F4F4" height="60"><span style="font-size:9pt;">번호</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">정가</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">인세율</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">합계수량</span></td>',
												'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">지급금액</span></td>',
												'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">지급인세</span></td>',
											'</tr>',
										'</table>',
										'<table id="mcRoyaltyUDData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="540" colspan="6" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><b>>> 총금액 <<</b></span></td>',
												'<td width="120" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><a id="sum_t"></a></span></td>',
												'<td width="125" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><a id="sum_t2"></a></span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "6_인쇄팝업":
			return [
			'<div style="width:780px; height:815px;">',
				'<div style="width:780px; height:100px; margin-left:15px;">',
					'<div style="width:780px; height:80px; padding:10px 0px 10px 0px;">',
						'<table id="popdata" border="0" cellpadding="0" cellspacing="0" width="780"></table>',
							
						
						'</div>',
				'</div>',
			'</div>',
			].join('');	
		
		case "6_지출결의서": //저자료 지급내역(상/하) -> jejak/kb/inse.php
			return [
				'<table border="0" width="720" id="btnRoyaltyUD" cellspacing="0" cellpadding="0">',
				'</table>',
			].join('');

		case "7": //월별 저자료 지출결의서 -> jejak/kb/inse3.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:153px; margin-left:15px;">',
					'<div style="width:780px; height:133px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="inse3.php">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>-&nbsp;',
										'<select name="ty" size="1" onChange="ChangeDate(29);">',	
										'</select> 년도&nbsp;',
										'<select name="tm" size="1" onChange="ChangeDate(29);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>&nbsp;&nbsp;월&nbsp;&nbsp;저자료</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle">',
										'<input type="text" size="5" name="pdate" maxlength="4">&nbsp;&nbsp;<input type="button" id="btnMonthlyRoyaltyPrint" value=" 인 쇄 "">',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="50" align="center" valign="middle" bgcolor="#F4F4F4" height="60"><span style="font-size:9pt;">번호</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
												'<td width="240" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
												'<td width="170" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">저자명</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">정가</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작부수</span></td>',
												'<td width="50" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">인세율</span></td>',
												'<td width="50" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="30" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">선택</span></td>',
											'</tr>',
											'<input type="hidden" name="pdate">',
										'</table>',
										'<table id="mcMonthlyRoyaltyData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td colspan="7" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><b>>> 총금액 <<</b></span></td>',
												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><a id="sum_t"></a></span></td>',
												'<td height="30" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:0pt;"></span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
						'</table>',					
					'</div>',
				'</div>',
			'</div>',
			].join('');
		case "7_인쇄팝업":
			return [
			'<div style="width:780px; height:815px;">',
				'<div style="width:780px; height:100px; margin-left:15px;">',
					'<div style="width:780px; height:80px; padding:10px 0px 10px 0px;">',
						'<table id="popdata" border="0" cellpadding="0" cellspacing="0" width="780"></table>',
							
						
						'</div>',
				'</div>',
			'</div>',
			].join('');	

		case "8": //저자료 지급 내역 ?? -> jejak/kb/inse2.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:153px; margin-left:15px;">',
					'<div style="width:780px; height:133px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="inse2.php">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>-&nbsp;',
										'<select name="ty" size="1" onChange="ChangeDate(28);">',		
										'</select> 년도&nbsp;',
										'<select name="tm" size="1" onChange="ChangeDate(28);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>&nbsp;&nbsp;월&nbsp;&nbsp;저자료 지급 내역</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="40" align="center" valign="middle" bgcolor="#F4F4F4" height="60"><span style="font-size:9pt;">번호</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">정가</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">인세율</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">합계수량</span></td>',
												'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">지급금액</span></td>',
												'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">지급인세</span></td>',
											'</tr>',
										'</table>',
										'<table id="mcRoyaltyData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="540" colspan="6" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><b>>> 총금액 <<</b></span></td>',
												'<td width="120" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><a id="sum_t_1"></a></span></td>',
												'<td width="125" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><a id="sum_t_2"></a></span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
						'</table>',					
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "10": //구매단가입력 -> jejak/su/301.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:540px; margin-left:15px;">',
					'<div style="width:780px; height:520px; padding:10px 0px 10px 0px;">',
						'<form name="frmMain">',
							'<table border="0" cellpadding="0" cellspacing="0" width="720" height="500">',
								'<tr>',
									'<td width="720" valign="middle">',
										'<table border="0" cellpadding="0" cellspacing="0" width="720" height="30">',
											'<tr>',
												'<td width="720" height="30" align="center" valign="middle"><b><span style="font-size:13pt;">구매 단가 계산</span></b></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" valign="middle" align="center">',
										'<table border="0" cellspacing="0" width="290" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="90" bgcolor="white" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">작업년월</font></span></td>',
												'<td width="100" height="30" align="center"><p style="margin-left:0px;">',
													'<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:96px;" name="date1" maxlength="4"></p>',
												'</td>',
												'<td width="100" height="30" align="center">',
													'<input type="button" value=" 실 행 " onClick="javascript:PurchasePrice();">',
												'</td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
							'</table>',
						'</form>',
						'<div id="Lay1" name="Layer1" style="visibility:hidden; position:absolute; width:300pt height:300pt; top:210pt; left:400pt;">',
							'<img src="/resources/style/images/jejak/time_02.gif" width="300" height="300" border="0">',
						'</div>',
						'<div>',
							'<iframe name="tFrm" width="0" height="0"></iframe>',
						'</div>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "11": //도서 수량.금액 집계 -> jejak/su/302.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:540px; margin-left:15px;">',
					'<div style="width:780px; height:520px; padding:10px 0px 10px 0px;">',
						'<form name="frmMain">',
							'<table border="0" cellpadding="0" cellspacing="0" width="720" height="500">',
								'<tr>',
									'<td width="720" valign="middle">',
										'<table border="0" cellpadding="0" cellspacing="0" width="720" height="30">',
											'<tr>',
												'<td width="720" height="30" align="center" valign="middle"><b><span style="font-size:13pt;">도서 수량/금액 집계</span></b></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" valign="middle" align="center">',
										'<table border="0" cellspacing="0" width="290" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="90" bgcolor="white" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">작업년월</font></span></td>',
												'<td width="100" height="30" align="center"><p style="margin-left:0px;">',
													'<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:96px;" name="date1" maxlength="4" onKeypress="if(event.keyCode == 13){javascript:chkDate();}"></p>',
												'</td>',
												'<td width="100" height="30" align="center">',
													'<input type="button" value=" 실 행 " onClick="javascript:BookQuantityAmountTotal()">',
												'</td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
							'</table>',
						'</form>',
						'<div id="Lay1" name="Layer1" style="visibility:hidden; position:absolute; width:300pt height:300pt; top:210pt; left:400pt;">',
							'<img src="/resources/style/images/jejak/time_02.gif" width="300" height="300" border="0">',
						'</div>',
						'<div>',
							'<iframe name="tFrm" width="0" height="0"></iframe>',
						'</div>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "12": //도서금액집계 -> jejak/su/303.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:540px; margin-left:15px;">',
					'<div style="width:780px; height:520px; padding:10px 0px 10px 0px;">',
						'<form name="frmMain">',
							'<table border="0" cellpadding="0" cellspacing="0" width="720" height="500">',
								'<tr>',
									'<td width="720" valign="middle">',
										'<table border="0" cellpadding="0" cellspacing="0" width="720" height="30">',
											'<tr>',
												'<td width="720" height="30" align="center" valign="middle"><b><span style="font-size:13pt;">도서 금액 집계</span></b></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" valign="middle" align="center">',
										'<table border="0" cellspacing="0" width="290" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="90" bgcolor="white" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">작업년월</font></span></td>',
												'<td width="100" height="30" align="center"><p style="margin-left:0px;">',
													'<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:96px;" name="date1" maxlength="4" onKeypress="if(event.keyCode == 13){javascript:chkDate();}"></p>',
												'</td>',
												'<td width="100" height="30" align="center">',
													'<input type="button" value=" 실 행 " onClick="javascript:BookAmountTotal()">',
												'</td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
							'</table>',
						'</form>',
						'<div id="Lay1" name="Layer1" style="visibility:hidden; position:absolute; width:300pt height:300pt; top:210pt; left:400pt;">',
							'<img src="/resources/style/images/jejak/time_02.gif" width="300" height="300" border="0">',
						'</div>',
						'<div>',
							'<iframe name="tFrm" width="0" height="0"></iframe>',
						'</div>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			

		case "14": //주은교육 제작현황 -> jejak/kb/juen.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:123px; margin-left:15px;">',
					'<div style="width:780px; height:103px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40">',
									'<form name="dform" method="get" action="juen.php">',
										'<table border="0" cellpadding="0" cellspacing="0" width="780">',
											'<tr>',
												'<td width="10"></td>',
												'<td width="65">',
													'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="ChangeDate(27);"></select>',
												'</td>',
												'<td width="20" align="left"><span style="font-size:9pt;">년</span></td>',
												'<td width="65">',
													'<select name="tm" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="ChangeDate(27);">',
														'<option value="01">01</option>',
														'<option value="02">02</option>',
														'<option value="03">03</option>',
														'<option value="04">04</option>',
														'<option value="05">05</option>',
														'<option value="06">06</option>',
														'<option value="07">07</option>',
														'<option value="08">08</option>',
														'<option value="09">09</option>',
														'<option value="10">10</option>',
														'<option value="11">11</option>',
														'<option value="12">12</option>',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">월</span></td>',
												'<td width="245" align="left"><b><span style="font-size:9pt;"> 주은교육 도서제작현황</span></b></td>',
												'<td width="340" align="right"><input type="button" id="PopUpPrint" value=" 인 쇄 "></td>',
											'</tr>',
										'</table>',
									'</form>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="780">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="60" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">순번</span></td>',
											'<td width="320" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작일</span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작부수</span></td>',
											'<td width="80" height="30" align="right" style="padding-right:15pt" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">인세율</span></td>',
											'<td width="137" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">인세금액</span></td>',
										'</tr>',
									'</table>',
									'<table id="mcJueunData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="640" colspan="5" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt; letter-spacing:50pt;">합계</span></td>',
											'<td width="137" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><a id="sum"></a></span></td>',
										'</tr>',
									'</table>',
								'</td>',
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "14_프린터팝업": //원친징수 인쇄팝업
			return [
			'<div style="width:780px; height:815px;">',
				'<div style="width:780px; height:120px; margin-left:15px;">',
					'<div style="width:780px; height:100px; padding:10px 0px 10px 0px;">',
						'<table id="popdata" border="0" cellpadding="0" cellspacing="0" width="720"></table>',
					'</div>',
				'</div>',
			'</div>',
		].join('');
		
		default:
			break;
	}
}