function jmenu7(val) { //월결산자료
	switch (val) {
		case "0": //도서별 원가계산서 -> jejak/kb/ex.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:123px; margin-left:15px;">',
					'<div style="width:780px; height:103px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40">',
									'<form name="dform" method="get" action="ex.php">',
										'<table border="0" cellpadding="0" cellspacing="0" width="780">',
											'<tr>',
												'<td width="10"></td>',
												'<td width="65">',
													'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="this.form.submit();">',
									
													'</select>',
												'</td>',
												'<td width="20" align="left"><span style="font-size:9pt;">년</span></td>',
												'<td width="65">',
													'<select name="tm" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="this.form.submit();">',
														'<option value="01">01</option>',
														'<option value="02">02</option>',
														'<option value="03">03</option>',
														'<option value="04">04</option>',
														'<option value="05">05</option>',
														'<option value="06">06</option>',
														'<option value="07">07</option>',
														'<option value="08">08</option>',
														'<option value="09">09</option>',
														'<option value="10">10</option>',
														'<option value="11">11</option>',
														'<option value="12">12</option>',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">월</span></td>',
												'<td width="65">',
													'<select name="td" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="this.form.submit();">',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">일</span></td>',
												'<td width="155" align="left"><b><span style="font-size:9pt;"> 원가 계산서</span></b></td>',
												'<td width="340" align="right">',
													'<input type="button" value="용지대 계산" onClick="javascript:CalcYJ2();">&nbsp;&nbsp;&nbsp;',
													'<input type="button" value="모두 인쇄" onClick="javascript:PrintAll();">',
												'</td>',
											'</tr>',
										'</table>',
									'</form>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="780">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="60" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">제작번호</span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작일</span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
											'<td width="320" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
											'<td width="80" height="30" align="right" style="padding-right:15pt" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작부수</span></td>',
											'<td width="137" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">메뉴</span></td>',
										'</tr>',
										'<tr>',
											'<td width="60" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=$row[crnum]?></span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=date("Y-m-d", $row[bdate]);?></span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=$row[bcode]?>-<?=$row[bucode]?></span></td>',
											'<td width="320" height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-left:5pt;"><a href="ex_view.php?uid=<?=$row[uid]?>&ty=<?=$ty?>&tm=<?=$tm?>&td=<?=$td?>&page=<?=$page?>" class="n"><?=$row[bname]?></a></span></td>',
											'<td width="80" height="30" align="right" style="padding-right:15pt" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=number_format($row[bnum]);?></span></td>',
											'<td width="137" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">',										
												'<input type="button" value="용지대 계산" onClick="javascript:CalcYJ();"></span>',           
											'</td>',
										'</tr>',
									'</table>',
								'</td>',
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "1": //잡물 원가계산서 -> jejak/cu/ex_j.htm
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:123px; margin-left:15px;">',
					'<div style="width:780px; height:103px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40">',
									'<form name="dform" method="post" action="ex_j.php">',
										'<table border="0" cellpadding="0" cellspacing="0" width="780">',
											'<tr>',
												'<td width="10"></td>',
												'<td width="65">',
													'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="this.form.submit();">',
											
													'</select>',
												'</td>',
												'<td width="20" align="left"><span style="font-size:9pt;">년</span></td>',
												'<td width="65">',
													'<select name="tm" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="this.form.submit();">',
														'<option value="01">01</option>',
														'<option value="02">02</option>',
														'<option value="03">03</option>',
														'<option value="04">04</option>',
														'<option value="05">05</option>',
														'<option value="06">06</option>',
														'<option value="07">07</option>',
														'<option value="08">08</option>',
														'<option value="09">09</option>',
														'<option value="10">10</option>',
														'<option value="11">11</option>',
														'<option value="12">12</option>',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">월</span></td>',
												'<td width="65">',
													'<select name="td" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="this.form.submit();">',
														//'<option value="<?=date("d", $row[JBDATE])?>"><?=date("d", $row[JBDATE])?></option>',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">일</span></td>',
												'<td width="155" align="left"><b><span style="font-size:9pt;">잡물 원가 계산서</span></b></td>',
												'<td width="340" align="right">',				
												'<input type="button" value="모두 인쇄" onClick="javascript:PrintAll();"></td>',
											'</tr>',
										'</table>',
									'</form>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="780">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="60" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">제작번호</span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작일</span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
											'<td width="320" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
											'<td width="80" height="30" align="right" style="padding-right:15pt" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작부수</span></td>',
											'<td width="137" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">메뉴</span></td>',
										'</tr>',
										'<tr>',
											'<td width="60" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=$row[UID]?></span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=date("Y-m-d",$row[JBDATE])?></span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">&nbsp;</span></td>',
											'<td width="320" height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-left:5pt;"><a href="exj_view.php?uid=<?=$row[UID]?>&ty=<?=$ty?>&tm=<?=$tm?>&td=<?=$td?>&page=<?=$page?>" class="n"><?=$row[JBNAME]?></a></span></td>',
											'<td width="80" height="30" align="right" style="padding-right:15pt" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=number_format($row[JBAMNT]);?></span></td>',
											'<td width="137" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">',                        
												'<input type="button" value="용지대 계산" onClick="javascript:CalcYJ();"></span>',
											'</td>',
										'</tr>',
									'</table>',
								'</td>',
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "2": //품목별 원재료명세서(월별) -> jejak/kb/yj_ms.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:194px; margin-left:15px;">',
					'<div style="width:780px; height:174px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="yj_ms.php">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>-&nbsp;',
										'<select name="sy" size="1" onChange="this.form.submit();">',
											'<!-- 임시 -->',	
											'<option value="2020">2020</option>',
											'<option value="2019">2019</option>',	
										'</select> 년 &nbsp;',
										'<select name="sm" size="1" onChange="this.form.submit();">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;원재료 명세서</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle">',
										'<input type="button" value=" 인 쇄 " onClick="javascript:ms_pr();">',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="80" align="center" valign="middle" bgcolor="#F4F4F4" height="60" rowspan="2"><span style="font-size:9pt;">원재료</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">기초재고</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">입고</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">출고</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">기말재고</span></td>',
											'</tr>',
											'<tr>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
											'</tr>',
											'<tr>',
												'<td width="80" align="center" valign="middle" bgcolor="white" height="30"><span style="font-size:9pt;"><?=$row[wjname]?></span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num1) echo(number_format($num1) . " R ")?><?=$num2?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($row[AMNT1])?></span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num3) echo(number_format($num3) . " R ")?><?=$num4?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($row[AMNT2])?></span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num5) echo(number_format($num5) . " R ")?><?=$num6?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($row[AMNT3])?></span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num7) echo(number_format($num7) . " R ")?><?=$num8?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($row[AMNT4])?></span></td>',
											'</tr>',
											'<tr>',
												'<td width="80" align="center" valign="middle" bgcolor="white" height="30"><span style="font-size:9pt;">합계</span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num1) echo(number_format($num1) . " R ")?><?=$num2?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($samnt1)?></span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num3) echo(number_format($num3) . " R ")?><?=$num4?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($samnt2)?></span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num5) echo(number_format($num5) . " R ")?><?=$num6?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($samnt3)?></span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num7) echo(number_format($num7) . " R ")?><?=$num8?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($samnt4)?></span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="780" colspan="2" height="40" align="center" valign="bottom">',
										'<input type="button" value=" 새로 작성 " onClick="javascript:Mk_New();">',
									'</td>',								
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
		
		case "3": //품목별 원재료명세서(기간) -> jejak/kb/yj_ms3.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:194px; margin-left:15px;">',
					'<div style="width:780px; height:174px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="yj_ms3.php">',
								'<tr>',
									'<td width="590" height="40"><p><span style="font-size:9pt;"><b>-&nbsp;',
										'<select name="sy1" size="1" onChange="this.form.submit();">',
											'<!-- 임시 -->',	
											'<option value="2020">2020</option>',
											'<option value="2019">2019</option>',	
										'</select> 년&nbsp;',
										'<select name="sm1" size="1" onChange="this.form.submit();">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월&nbsp;~&nbsp;',           
										'<select name="sm2" size="1" onChange="this.form.submit();">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;원재료 명세서</b></span></p>',
									'</td>',
									'<td width="190" height="40" align="right" valign="middle">',
										'<input type="button" value=" 인 쇄 " onClick="javascript:ms_pr();">',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="80" align="center" valign="middle" bgcolor="#F4F4F4" height="60" rowspan="2"><span style="font-size:9pt;">원재료</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">기초재고</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">입고</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">출고</span></td>',
												'<td width="175" height="30" align="center" valign="middle" bgcolor="#F4F4F4" colspan="2"><span style="font-size:9pt;">기말재고</span></td>',
											'</tr>',
											'<tr>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="85" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
											'</tr>',
											'<tr>',
												'<td style="cursor:hand" onClick="javascript:View_All();" width="80" align="center" valign="middle" bgcolor="white" height="30"><span style="font-size:9pt;"><?=$row[wjname]?></span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num1) echo(number_format($num1) . " R ")?><?=$num2?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($row[AMNT1])?></span></td>',
												'<td style="cursor:hand" onClick="javascript:View_Com();" width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num3) echo(number_format($num3) . " R ")?><?=$num4?></span></td>',
												'<td style="cursor:hand" onClick="javascript:View_Com();" width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($row[AMNT2])?></span></td>',
												'<td style="cursor:hand" onClick="javascript:View_Com();" width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num5) echo(number_format($num5) . " R ")?><?=$num6?></span></td>',
												'<td style="cursor:hand" onClick="javascript:View_Com();" width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($row[AMNT3])?></span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num7) echo(number_format($num7) . " R ")?><?=$num8?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($row[AMNT4])?></span></td>',
											'</tr>',
											'<tr style="display:none;" id="in<?=$ii?>">',
												'<td width="780" bgcolor="#FFF5F5" colspan="9" align="center" valign="middle" bgcolor="white">',
													'<table width="520" border="0" cellpadding="0" cellspacing="0">',
														'<tr>',
															'<td width="520" colspan="4" height="5"></td>',
														'</tr>',
														'<tr>',
															'<td width="80" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">일자</span></td>',
															'<td width="240" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA; border-left: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">구매처</span></td>',
															'<td width="100" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA; border-left: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">수량</span></td>',
															'<td width="100" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA; border-left: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">금액</span></td>',
														'</tr>',
														'<tr>',
															'<td width="80" height="15" align="center"><span style="font-size:8pt;"><?=date("y. m. d",$crow[date])?></span></td>',
															'<td width="240" height="15" align="left"><span style="font-size:8pt; padding-left:3pt; letter-spacing:2pt;"><?=$custname?></span></td>',
															'<td width="100" height="15" align="center">',
																'<table border="0" width="100" cellpadding="0" cellspacing="0">',
																	'<tr>',
																		'<td width="70" align="right"><span style="font-size:8pt; padding-right:3pt;"><?=$tnum1?></span></td>',
																		'<td width="30" align="left"><span style="font-size:8pt; padding-left:0pt;"><?=$tnum2?></span></td>',
																	'</tr>',
																'</table>',
															'</td>',
															'<td width="100" height="15" align="right"><span style="font-size:8pt; padding-right:10pt;"><?=number_format($crow[tprice])?></span></td>',
														'</tr>',
														'<tr>',
															'<td width="320" colspan="2" height="15" align="center"><span style="font-size:8pt; letter-spacing:13pt;"><입고합계></span></td>',
															'<td width="100" height="15" align="center">',
																'<table border="0" width="100" cellpadding="0" cellspacing="0">',
																	'<tr>',
																		'<td width="70" align="right"><span style="font-size:8pt; padding-right:3pt;"><?=$tnum1?></span></td>',
																		'<td width="30" align="left"><span style="font-size:8pt; padding-left:0pt;"><?=$tnum2?></span></td>',
																	'</tr>',
																'</table></td>',
															'<td width="100" height="15" align="right"><span style="font-size:8pt; padding-right:10pt;"><?=number_format($tsum2)?></span></td>',
														'</tr>',
														'<tr>',
															'<td width="520" colspan="4" height="5"></td>',
														'</tr>',	
													'</table>',
												'</td>',
											'</tr>',
											'<tr style="display:none;" id="out<?=$ii?>">',
												'<td width="780" bgcolor="#F5F5FF" colspan="9" align="center" valign="middle" bgcolor="white">',
													'<table width="520" border="0" cellpadding="0" cellspacing="0">',
														'<tr>',
															'<td width="520" colspan="4" height="5"></td>',
														'</tr>',
														'<tr>',
															'<td width="80" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">일자</span></td>',
															'<td width="240" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA; border-left: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">출고내역</span></td>',
															'<td width="100" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA; border-left: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">수량</span></td>',
															'<td width="100" height="15" style="border-top: 1px solid #AAAAAA; border-bottom: 1px solid #AAAAAA; border-left: 1px solid #AAAAAA;" align="center"><span style="font-size:8pt; letter-spacing:20pt;">금액</span></td>',
														'</tr>',
														'<tr>',
															'<td width="80" height="15" align="center"><span style="font-size:8pt;"><?=date("y. m. d",$crow[date])?></span></td>',
															'<td width="240" height="15" align="left"><span style="font-size:8pt; padding-left:3pt;"><?=$crow[comment]?></span></td>',
															'<td width="100" height="15" align="center">',
																'<table border="0" width="100" cellpadding="0" cellspacing="0">',
																	'<tr>',
																		'<td width="70" align="right"><span style="font-size:8pt; padding-right:3pt;"><?=$tnum1?></span></td>',
																		'<td width="30" align="left"><span style="font-size:8pt; padding-left:0pt;"><?=$tnum2?></span></td>',
																	'</tr>',
																'</table>',
															'</td>',
															'<td width="100" height="15" align="right"><span style="font-size:8pt; padding-right:10pt;"><?=number_format($crow[tprice])?></span></td>',
														'</tr>',
														'<tr>',
															'<td width="320" colspan="2" height="15" align="center"><span style="font-size:8pt; letter-spacing:13pt;"><출고합계></span></td>',
															'<td width="100" height="15" align="center">',
																'<table border="0" width="100" cellpadding="0" cellspacing="0">',
																	'<tr>',
																		'<td width="70" align="right"><span style="font-size:8pt; padding-right:3pt;"><?=$tnum1?></span></td>',
																		'<td width="30" align="left"><span style="font-size:8pt; padding-left:0pt;"><?=$tnum2?></span></td>',
																	'</tr>',
																'</table>',
															'</td>',
															'<td width="100" height="15" align="right"><span style="font-size:8pt; padding-right:10pt;"><?=number_format($tsum2)?></span></td>',
														'</tr>',
														'<tr>',
															'<td width="520" colspan="4" height="5"></td>',
														'</tr>',	
													'</table>',
												'</td>',
											'</tr>',
											'<tr>',
												'<td width="80" align="center" valign="middle" bgcolor="white" height="30"><span style="font-size:9pt;">합계</span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num1) echo(number_format($num1) . " R ")?><?=$num2?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($samnt1)?></span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num3) echo(number_format($num3) . " R ")?><?=$num4?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($samnt2)?></span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num5) echo(number_format($num5) . " R ")?><?=$num6?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($samnt3)?></span></td>',
												'<td width="85" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?if ($num7) echo(number_format($num7) . " R ")?><?=$num8?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($samnt4)?></span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="780" colspan="2" height="40" align="center" valign="bottom">',
										'<input type="button" value=" 새로 작성 " onClick="javascript:Mk_New();">',
									'</td>',	
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "4": //제조비명세표 -> jejak/kb/new_jejo.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:960px; height:213px; margin-left:15px;">',
					'<div style="width:960px; height:193px; padding:10px 0px 10px 0px;">',
						'<div style="width:780px; height:30px; display:table-cell; vertical-align:middle; font-size:13pt;"><b>- 제조비명세표</b></div>',
						
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "5": //거래처별 지불명세서 -> jejak/kb/jejo2.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:870px; height:194px; margin-left:15px;">',
					'<div style="width:870px; height:174px; padding:10px 0px 10px 0px;">',
						'<div style="width:780px; height:30px; display:table-cell; vertical-align:middle; font-size:13pt;"><b>- 거래처별 지불명세서</b></div>',

					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "6": //저자료 지급내역(상/하) -> jejak/kb/inse.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:112px; margin-left:15px;">',
					'<div style="width:780px; height:102px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="inse.php">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>-&nbsp;',
										'<select name="sy" size="1" onChange="this.form.submit();">',
											'<!-- 임시 -->',	
											'<option value="2020">2020</option>',
											'<option value="2019">2019</option>',	
										'</select> 년도&nbsp;',
										'<select name="gubn" size="1" onChange="this.form.submit();">',
											'<option value="1">국내</option>',
											'<option value="2">해외</option>',
										'</select>&nbsp;&nbsp;',
										'<select name="gubn2" size="1" onChange="this.form.submit();">',
											'<option value="1">상반기</option>',
											'<option value="2">하반기</option>',
										'</select>&nbsp;&nbsp;저자료 지급 내역</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle">',
										'<input type="button" value=" 인 쇄 " onClick="javascript:ms_pr();">&nbsp;',
										'<input type="button" value=" EXCEL " onClick="javascript:Exc();">&nbsp;',
										'<input type="button" value=" 지출결의서 " onClick="javascript:ms_pr2();">',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="40" align="center" valign="middle" bgcolor="#F4F4F4" height="60"><span style="font-size:9pt;">번호</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">정가</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">인세율</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">합계수량</span></td>',
												'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">지급금액</span></td>',
												'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">지급인세</span></td>',
											'</tr>',
											'<tr>',
												'<td width="40" align="center" valign="middle" bgcolor="white" height="30"><span style="font-size:9pt;"><?=$rec_num?></span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=$row[SBBOOK]?></span></td>',
												'<td width="220" height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-left:5pt;"><?=$row[SBNAME]?></span></td>',
												'<td width="60" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($row[SBUPRC])?></span></td>',
												'<td width="60" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=$b_inse?><?if ($row[SBHJGB] == 1) echo("반"); else echo("일");?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($sum_p)?></span></td>',
												'<td width="120" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($sum_a)?></span></td>',
												'<td width="125" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($sum_a)?></span></td>',
											'</tr>',
											'<tr>',
												'<td width="540" colspan="6" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><b>>> 총금액 <<</b></span></td>',
												'<td width="120" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($sum_t)?></span></td>',
												'<td width="125" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($sum_t)?></span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "7": //월별 저자료 지출결의서 -> jejak/kb/inse3.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:153px; margin-left:15px;">',
					'<div style="width:780px; height:133px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="inse3.php">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>-&nbsp;',
										'<select name="sy" size="1" onChange="this.form.submit();">',
											'<!-- 임시 -->',	
											'<option value="2020">2020</option>',
											'<option value="2019">2019</option>',	
										'</select> 년도&nbsp;',
										'<select name="gubn" size="1" onChange="this.form.submit();">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>&nbsp;&nbsp;월&nbsp;&nbsp;저자료</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle">',
										'<input type="text" size="5" name="pdate" maxlength="4">&nbsp;&nbsp;<input type="button" value=" 인 쇄 " onClick="javascript:ms_pr();">',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="50" align="center" valign="middle" bgcolor="#F4F4F4" height="60"><span style="font-size:9pt;">번호</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
												'<td width="240" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
												'<td width="170" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">저자명</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">정가</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작부수</span></td>',
												'<td width="50" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">인세율</span></td>',
												'<td width="50" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">금액</span></td>',
												'<td width="30" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">선택</span></td>',
											'</tr>',
											'<form name="frmChk" method="post">',
											'<input type="hidden" name="pdate">',
											'<tr>',
												'<td align="center" valign="middle" bgcolor="white" height="30"><span style="font-size:9pt;"><?=$rec_num?></span></td>',
												'<td height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=$brow[SBBOOK]?></span></td>',
												'<td height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-left:5pt;"><?=$brow[SBNAME]?></span></td>',
												'<td height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-left:5pt;"><?=$juja?></span></td>',
												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($brow[SBUPRC])?></span></td>',
												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($row[bnum])?></span></td>',
												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($inse)?></span></td>',
												'<td width="125" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($sum_a)?></span></td>',
												'<td width="125" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:0pt;">',
													'<input type="checkbox" name="chk[]" value="<?=$row[uid]?>"></span>',
												'</td>',
											'</tr>',
											'</form>',
											'<tr>',
												'<td colspan="7" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><b>>> 총금액 <<</b></span></td>',
												'<td height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($sum_t)?></span></td>',
												'<td height="30" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:0pt;"></span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
						'</table>',					
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "8": //저잘료 지급 내역 ?? -> jejak/kb/inse2.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:153px; margin-left:15px;">',
					'<div style="width:780px; height:133px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="inse2.php">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>-&nbsp;',
										'<select name="sy" size="1" onChange="this.form.submit();">',
											'<!-- 임시 -->',	
											'<option value="2020">2020</option>',
											'<option value="2019">2019</option>',		
										'</select> 년도&nbsp;',
										'<select name="gubn" size="1" onChange="this.form.submit();">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>&nbsp;&nbsp;월&nbsp;&nbsp;저자료 지급 내역</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="40" align="center" valign="middle" bgcolor="#F4F4F4" height="60"><span style="font-size:9pt;">번호</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서코드</span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">정가</span></td>',
												'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">인세율</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">합계수량</span></td>',
												'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">지급금액</span></td>',
												'<td width="120" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">지급인세</span></td>',
											'</tr>',
											'<tr>',
												'<td width="40" align="center" valign="middle" bgcolor="white" height="30"><span style="font-size:9pt;"><?=$rec_num?></span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=$row[SBBOOK]?></span></td>',
												'<td width="220" height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-left:5pt;"><?=$row[SBNAME]?></span></td>',
												'<td width="60" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($row[SBUPRC])?></span></td>',
												'<td width="60" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=$b_inse?><?if ($row[SBHJGB] == 1) echo("반"); else echo("일");?></span></td>',
												'<td width="90" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($sum_p)?></span></td>',
												'<td width="120" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($sum_a)?></span></td>',
												'<td width="125" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($sum_a)?></span></td>',
											'</tr>',
											'<tr>',
												'<td width="540" colspan="6" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><b>>> 총금액 <<</b></span></td>',
												'<td width="120" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($sum_t)?></span></td>',
												'<td width="125" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($sum_t)?></span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
						'</table>',					
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "10": //구매단가입력 -> jejak/su/301.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:540px; margin-left:15px;">',
					'<div style="width:780px; height:520px; padding:10px 0px 10px 0px;">',
						'<form name="frmMain">',
							'<table border="0" cellpadding="0" cellspacing="0" width="720" height="500">',
								'<tr>',
									'<td width="720" valign="middle">',
										'<table border="0" cellpadding="0" cellspacing="0" width="720" height="30">',
											'<tr>',
												'<td width="720" height="30" align="center" valign="middle"><b><span style="font-size:13pt;">구매 단가 계산</span></b></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" valign="middle" align="center">',
										'<table border="0" cellspacing="0" width="290" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="90" bgcolor="white" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">작업년월</font></span></td>',
												'<td width="100" height="30" align="center"><p style="margin-left:0px;">',
													'<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:96px;" name="date1" maxlength="4"></p>',
												'</td>',
												'<td width="100" height="30" align="center">',
													'<input type="button" value=" 실 행 " onClick="javascript:SendFrm();">',
												'</td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
							'</table>',
						'</form>',
						'<div id="Lay1" name="Layer1" style="visibility:hidden; position:absolute; width:300pt height:300pt; top:210pt; left:400pt;">',
							'<img src="/resources/style/images/jejak/time_02.gif" width="300" height="300" border="0">',
						'</div>',
						'<div>',
							'<iframe name="tFrm" width="0" height="0"></iframe>',
						'</div>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "11": //도서 수량.금액 집계 -> jejak/su/302.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:540px; margin-left:15px;">',
					'<div style="width:780px; height:520px; padding:10px 0px 10px 0px;">',
						'<form name="frmMain">',
							'<table border="0" cellpadding="0" cellspacing="0" width="720" height="500">',
								'<tr>',
									'<td width="720" valign="middle">',
										'<table border="0" cellpadding="0" cellspacing="0" width="720" height="30">',
											'<tr>',
												'<td width="720" height="30" align="center" valign="middle"><b><span style="font-size:13pt;">도서 수량/금액 집계</span></b></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" valign="middle" align="center">',
										'<table border="0" cellspacing="0" width="290" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="90" bgcolor="white" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">작업년월</font></span></td>',
												'<td width="100" height="30" align="center"><p style="margin-left:0px;">',
													'<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:96px;" name="date1" maxlength="4" onKeypress="if(event.keyCode == 13){javascript:chkDate();}"></p>',
												'</td>',
												'<td width="100" height="30" align="center">',
													'<input type="button" value=" 실 행 " onClick="javascript:SendFrm();">',
												'</td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
							'</table>',
						'</form>',
						'<div id="Lay1" name="Layer1" style="visibility:hidden; position:absolute; width:300pt height:300pt; top:210pt; left:400pt;">',
							'<img src="/resources/style/images/jejak/time_02.gif" width="300" height="300" border="0">',
						'</div>',
						'<div>',
							'<iframe name="tFrm" width="0" height="0"></iframe>',
						'</div>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "12": //도서금액집계 -> jejak/su/303.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:540px; margin-left:15px;">',
					'<div style="width:780px; height:520px; padding:10px 0px 10px 0px;">',
						'<form name="frmMain">',
							'<table border="0" cellpadding="0" cellspacing="0" width="720" height="500">',
								'<tr>',
									'<td width="720" valign="middle">',
										'<table border="0" cellpadding="0" cellspacing="0" width="720" height="30">',
											'<tr>',
												'<td width="720" height="30" align="center" valign="middle"><b><span style="font-size:13pt;">도서 금액 집계</span></b></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" valign="middle" align="center">',
										'<table border="0" cellspacing="0" width="290" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="90" bgcolor="white" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">작업년월</font></span></td>',
												'<td width="100" height="30" align="center"><p style="margin-left:0px;">',
													'<INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:96px;" name="date1" maxlength="4" onKeypress="if(event.keyCode == 13){javascript:chkDate();}"></p>',
												'</td>',
												'<td width="100" height="30" align="center">',
													'<input type="button" value=" 실 행 " onClick="javascript:SendFrm();">',
												'</td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
							'</table>',
						'</form>',
						'<div id="Lay1" name="Layer1" style="visibility:hidden; position:absolute; width:300pt height:300pt; top:210pt; left:400pt;">',
							'<img src="/resources/style/images/jejak/time_02.gif" width="300" height="300" border="0">',
						'</div>',
						'<div>',
							'<iframe name="tFrm" width="0" height="0"></iframe>',
						'</div>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "14": //주은교육 제작현황 -> jejak/kb/juen.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:123px; margin-left:15px;">',
					'<div style="width:780px; height:103px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40">',
									'<form name="dform" method="get" action="juen.php">',
										'<table border="0" cellpadding="0" cellspacing="0" width="780">',
											'<tr>',
												'<td width="10"></td>',
												'<td width="65">',
													'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="this.form.submit();">',
														'<!-- 임시 -->',	
														'<option value="2020">2020</option>',
														'<option value="2019">2019</option>',	
													'</select>',
												'</td>',
												'<td width="20" align="left"><span style="font-size:9pt;">년</span></td>',
												'<td width="65">',
													'<select name="tm" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="this.form.submit();">',
														'<option value="01">01</option>',
														'<option value="02">02</option>',
														'<option value="03">03</option>',
														'<option value="04">04</option>',
														'<option value="05">05</option>',
														'<option value="06">06</option>',
														'<option value="07">07</option>',
														'<option value="08">08</option>',
														'<option value="09">09</option>',
														'<option value="10">10</option>',
														'<option value="11">11</option>',
														'<option value="12">12</option>',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">월</span></td>',
												'<td width="245" align="left"><b><span style="font-size:9pt;"> 주은교육 도서제작현황</span></b></td>',
												'<td width="340" align="right"><input type="button" value=" 인 쇄 " onClick="javascript:PrintAll();"></td>',
											'</tr>',
										'</table>',
									'</form>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="780">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="60" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">순번</span></td>',
											'<td width="320" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작일</span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">제작부수</span></td>',
											'<td width="80" height="30" align="right" style="padding-right:15pt" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">인세율</span></td>',
											'<td width="137" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">인세금액</span></td>',
										'</tr>',
										'<tr>',
											'<td width="60" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=$rec_no?></span></td>',
											'<td width="320" height="30" align="left" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-left:5pt;"><?=$row[bname]?></span></td><?=date("Y-m-d", $row[bdate]);?></span></td>',
											'<td width="90" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=$row[bnum]?></span></td>',                    
											'<td width="80" height="30" align="right" style="padding-right:15pt" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=$crow[1]?></span></td>',
											'<td width="137" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=number_format($tprice)?></span></td>',
										'</tr>',
										'<tr>',
											'<td width="640" colspan="5" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt; letter-spacing:50pt;">합계</span></td>',
											'<td width="137" height="30" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;"><?=number_format($tsum)?></span></td>',
										'</tr>',
									'</table>',
								'</td>',
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
		
		default:
			break;
	}
}