function jmenu1(val) { //거래처관
	switch (val) {
		case "0": //등록관리 -> jejak/cu/cust_in.htm
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:324px; margin-left:15px;">',
					'<div style="width:780px; height:304px; padding:10px 0px 10px 0px;">',
						'<div style="width:780px; height:30px; display:table-cell; vertical-align:middle; font-size:13pt;"><b>- 거래처 등록</b></div>',
						//'<form name="form1" method="post" action="test.js" onsubmit="retrun chkAll();">',
							'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
								'<tr>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><font color="red"><b>코드</b></font></span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:120px;" name="wccode" autocomplete=off></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><font color="red"><b>업종</b></font></span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><select name="wcjob" style="font-family:돋움; font-size:9pt; width:120px;">',
										'<option value="">:::  선택  :::</option>',
										'<option value="인쇄">   인쇄</option>',
										'<option value="제본">   제본</option>',
										'<option value="코팅">   코팅</option>',
										'<option value="용지">   용지</option>',
										'<option value="증지">   증지</option>',
										'<option value="스티커">  스티커</option>',
										'<option value="CD">   CD</option>',
										'<option value="케이스">   케이스</option>',
										'<option value="비닐">   비닐</option>',
										'<option value="기타">   기타</option>',
										'<option value="0">------------</option>',
										'<option value="사보">   사보</option>',
										'<option value="출력">   출력</option>',
									'</select></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">대표자</span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:120px;" name="wcdeap"></td>',
								'</tr>',
								'<tr>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><font color="red"><b>거래처명</b></font></span></td>',
									'<td width="260" height="35" align="center" valign="middle" bgcolor="white" colspan="2"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:250px;" name="wcname" autocomplete=off></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">연락처</span></td>',
									'<td width="260" height="35" align="center" valign="middle" bgcolor="white" colspan="2"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:250px;" name="wctel" autocomplete=off></td>',
								'</tr>',
								'<tr>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">주소</span></td>',
									'<td width="650" height="35" align="center" valign="middle" bgcolor="white" colspan="5"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:640px;" name="wcjuso" autocomplete=off></td>',
								'</tr>',
								'<tr>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">계산서</span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><select name="tax" style="font-family:돋움; font-size:9pt; width:120px;">',
										'<option value="0">세금계산서</option>',
										'<option value="1"> 계산서 </option>',
									'</select></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><font color="red"><b>약칭</b></font></span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><INPUT style="text-align:left; padding-left:5pt; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:120px;" name="wcyakc" autocomplete=off></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">잔액</span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><INPUT style="text-align:right; padding-right:5pt; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:120px;" name="wcjana"></td>',
								'</tr>',
								'<tr>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><font color="red"><b>구매코드</b></font></span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><INPUT style="text-align:left; padding-right:5pt; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:120px;" name="wccode2" autocomplete=off></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">EMAIL</span></td>',
									'<td width="390" colspan="3" height="35" align="center" valign="middle" bgcolor="white"><INPUT style="text-align:left; padding-right:5pt; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:380px;" name="wcemail" autocomplete=off></td>',
								'</tr>',
							'</table>',
							'<div style="width:780px; height:24px; padding-top:53px; text-align:center;"><input type="button" onclick="javascript:InIt(1);" value="등  록"></div>',
						//'</form>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "0-수정": //등록관리 -> jejak/cu/cust_in.htm
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:324px; margin-left:15px;">',
					'<div style="width:780px; height:304px; padding:10px 0px 10px 0px;">',
						'<div style="width:780px; height:30px; display:table-cell; vertical-align:middle; font-size:13pt;"><b>- 거래처 등록</b></div>',
						//'<form name="form1" method="post" action="test.js" onsubmit="retrun chkAll();">',
							'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
								'<tr>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><font color="red"><b>코드</b></font></span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:120px;" name="wccode" autocomplete=off></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><font color="red"><b>업종</b></font></span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><select name="wcjob" style="font-family:돋움; font-size:9pt; width:120px;">',
										'<option value="">:::  선택  :::</option>',
										'<option value="인쇄">   인쇄</option>',
										'<option value="제본">   제본</option>',
										'<option value="코팅">   코팅</option>',
										'<option value="용지">   용지</option>',
										'<option value="증지">   증지</option>',
										'<option value="스티커">  스티커</option>',
										'<option value="CD">   CD</option>',
										'<option value="케이스">   케이스</option>',
										'<option value="비닐">   비닐</option>',
										'<option value="기타">   기타</option>',
										'<option value="0">------------</option>',
										'<option value="사보">   사보</option>',
										'<option value="출력">   출력</option>',
									'</select></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">대표자</span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:120px;" name="wcdeap"></td>',
								'</tr>',
								'<tr>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><font color="red"><b>거래처명</b></font></span></td>',
									'<td width="260" height="35" align="center" valign="middle" bgcolor="white" colspan="2"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:250px;" name="wcname" autocomplete=off></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">연락처</span></td>',
									'<td width="260" height="35" align="center" valign="middle" bgcolor="white" colspan="2"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:250px;" name="wctel" autocomplete=off></td>',
								'</tr>',
								'<tr>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">주소</span></td>',
									'<td width="650" height="35" align="center" valign="middle" bgcolor="white" colspan="5"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:640px;" name="wcjuso" autocomplete=off></td>',
								'</tr>',
								'<tr>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">계산서</span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><select name="tax" style="font-family:돋움; font-size:9pt; width:120px;">',
										'<option value="0">세금계산서</option>',
										'<option value="1"> 계산서 </option>',
									'</select></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><font color="red"><b>약칭</b></font></span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><INPUT style="text-align:left; padding-left:5pt; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:120px;" name="wcyakc" autocomplete=off></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">잔액</span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><INPUT style="text-align:right; padding-right:5pt; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:120px;" name="wcjana"></td>',
								'</tr>',
								'<tr>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><font color="red"><b>구매코드</b></font></span></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="white"><INPUT style="text-align:left; padding-right:5pt; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:120px;" name="wccode2" autocomplete=off></td>',
									'<td width="130" height="35" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">EMAIL</span></td>',
									'<td width="390" colspan="3" height="35" align="center" valign="middle" bgcolor="white"><INPUT style="text-align:left; padding-right:5pt; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:380px;" name="wcemail" autocomplete=off></td>',
								'</tr>',
							'</table>',
							'<div style="width:780px; height:24px; padding-top:53px; text-align:center;"><input type="button" id="btn_UpIt" value="수  정"></div>',
						//'</form>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "1": //목록관리 -> jejak/cu/cust.htm
			return [
			'<div id="cust" style="width:810px; height:815px;">',
				'<div style="width:780px; height:597px; margin-left:15px;">',
					'<div style="width:780px; height:304px; padding:10px 0px 10px 0px;">',
						'<div style="width:780px; height:30px; display:table-cell; vertical-align:middle; font-size:13pt;"><b>- 거래처 목록</b></div>',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" align="left" valign="top">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="45" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">코드</span></td>',
											'<td width="130" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">거래처명</span></td>',
											'<td width="45" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">약자</span></td>',
											'<td width="60" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">업종</span></td>',
											'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">연락처</span></td>',
											'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">잔액</span></td>',
											'<td width="240" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">주소</span></td>',
											'<td width="100" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">메뉴</span></td>',
										'</tr>',
									'</table>',
									'<table id="data" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'<table id="pagination" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0"></table>',			
								'</td>',
							'</tr>',
                        '</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "3": //IP 변경 -> jejak/cu/ch_ips.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:597px; margin-left:15px;">',
					'<div style="width:780px; height:416px; padding:10px 0px 10px 0px;">',
						'<div style="width:720px; height:400px; padding:18px 30px 18px 30px; text-align: center;">',
							'<div style="width:720px; height:149px; display:table-cell; vertical-align:middle; font-size:13pt;"><b>IP 변경</b></div>',
							'<div style="width:720px; height:241px; padding-top:10px">',
								//'<form name="frmMain" method="post" action="ips_m.php">',
									'<table border="0" cellpadding="0" cellspacing="0" width="720" height="400"></table>',
										'<tr>',
											'<td width="720" valign="middle" align="center">',
												'<table id="ip_table" border="1" cellspacing="0" width="350" bordercolordark="white" bordercolorlight="#CCCCCC"></table>', 
												'<table border="0" cellspacing="0" width="350" bordercolordark="white" bordercolorlight="#CCCCCC">',
													'<tr>',
														'<td width="350" height="60" align="center" valign="bottom">',
															'<input id="btn_UpIt" type="button" value=" 변 경 "></td>',
													'</tr>',
												'</table>',
											'</td>',
										'</tr>',
									'</table>',
								//'</form>',
							'</div>',
						'</div>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
		default:
			break;
	}
}