function jmenu9(val) {
	switch (val) {//"회계전표", "원천징수", " ", "도서별 월별집계", "년도별 월별집계", "도서별 제작현황", " ", "전기 이월 작업", " ", "미입고 도서", " ", "전도서재고조회"
		case "0": //회계전표 -> jejak/su/107.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:60px; margin-left:15px;">',
					'<div style="width:780px; height:40px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40">',
									'<form name="dform" method="post" action="107.php">',
										'<table border="0" cellpadding="0" cellspacing="0" width="780">',
											'<tr>',
												'<td width="10"></td>',
												'<td width="65">',
													'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;">',

													'</select>',
												'</td>',
												'<td width="20" align="left"><span style="font-size:9pt;">년</span></td>',
												'<td width="65">',
													'<select name="tm" size="1" style="font-family:굴림; font-size:9pt;  width:60;">',
														'<option value="01">01</option>',
														'<option value="02">02</option>',
														'<option value="03">03</option>',
														'<option value="04">04</option>',
														'<option value="05">05</option>',
														'<option value="06">06</option>',
														'<option value="07">07</option>',
														'<option value="08">08</option>',
														'<option value="09">09</option>',
														'<option value="10">10</option>',
														'<option value="11">11</option>',
														'<option value="12">12</option>',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">월</span></td>',
												'<td width="65" align="right"><span style="font-size:9pt;">회 계 전 표</span></td>',
												'<td width="30"></td>',
												'<td width="340" align="left">',
													'<input type="submit" value=" 보기 ">&nbsp;&nbsp;&nbsp;&nbsp;',
													'<input type="button" value=" 전표작성 " onClick="javascript:MakeAll();">&nbsp;&nbsp;',
													'<input type="button" value=" EXCEL " onClick="javascript:MakeEx();">',
												'</td>',
												'<td width="155" align="right"><input type="button" value=" 인 쇄 " onClick="javascript:PrintAll();"></td>',
											'</tr>',
										'</table>',
									'</form>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="780">',
									'<table border="0" cellspacing="2" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="390" align="center" valign="top" bgcolor="white" height="30">',
												'<table width="100%" border="1" cellspacing="0" cellpadding="0" bordercolor="white">',
													'<tr>',
														'<td style="border-bottom: 1px solid #C0C0C0" width="40" height="25" align="center"><span style="font-size:9pt;">월.일</span></td>',
														'<td style="border-bottom: 1px solid #C0C0C0; border-left: 1px solid #C0C0C0" height="25" width="260" align="center"><span style="font-size:9pt;">적 요</span></td>',
														'<td style="border-bottom: 1px solid #C0C0C0; border-left: 1px solid #C0C0C0" height="25" width="90" align="center"><span style="font-size:9pt;">금 액</span></td>',
													'</tr>',
													'<tr>',
														'<td style="border-bottom: 1px solid #C0C0C0" width="40" height="25" align="center" valign="middle"><span style="font-size:9pt;"><?=$mdate?></span></td>',
														'<td style="border-bottom: 1px solid #C0C0C0" width="260" height="25" align="left" valign="top"><span style="font-size:9pt; padding-left:3pt;"><?=$pdesc?><br> @ <?=number_format()?> X <?=number_format($pnum)?>부</span></td>',
														'<td style="border-bottom: 1px solid #C0C0C0" width="90" height="25" align="right" valign="middle"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($psum)?></span></td>',
													'</tr>',
													'<tr>',
														'<td style="border-bottom: 1px solid #C0C0C0" width="40" height="25" align="center"><span style="font-size:9pt; padding-left:0pt;"></span></td>',
														'<td style="border-bottom: 1px solid #C0C0C0" width="260" height="25" align="right"><span style="font-size:9pt; padding-right:5pt;">-- <?=$jab_str?> --</span></td>',
														'<td style="border-bottom: 1px solid #C0C0C0" width="90" height="25" align="right"><span style="font-size:9pt; padding-right:5pt;"><?=number_format($jab)?></span></td>',
													'</tr>',
												'</table>',
											'</td>',
											'<td width="390" align="center" valign="middle" bgcolor="white" height="30">',
												'<table width="100%" border="1" cellspacing="0" cellpadding="0" bordercolor="white">',
													'<tr>',
														'<td style="border-bottom: 1px solid #C0C0C0" width="40" height="25" align="center"><span style="font-size:9pt;">월.일</span></td>',
														'<td style="border-bottom: 1px solid #C0C0C0; border-left: 1px solid #C0C0C0" height="25" width="260" align="center"><span style="font-size:9pt;">적 요</span></td>',
														'<td style="border-bottom: 1px solid #C0C0C0; border-left: 1px solid #C0C0C0" height="25" width="90" align="center"><span style="font-size:9pt;">금 액</span></td>',
													'</tr>',
													'<tr>',
														'<td style="border-bottom: 1px solid #C0C0C0" width="40" height="25" align="center"><span style="font-size:9pt;"><?if ($j == 2) echo("$mdate");?></span></td>',
														'<td style="border-bottom: 1px solid #C0C0C0" width="260" height="25" align="right"><span style="font-size:9pt; padding-right:5pt;">( <?=$bigo?> )</span></td>',
														'<td style="border-bottom: 1px solid #C0C0C0" width="90" height="25" align="right"><span style="font-size:9pt; padding-right:5pt;"></span></td>',
													'</tr>',
												'</table>',
											'</td>',
										'</tr>',
									'</table>',
								'</td>',
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "1": //원천징수 -> jejak/su/401.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:395px; margin-left:15px;">',
					'<div style="width:780px; height:375px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40">',
									'<form name="dform" method="get" action="401.php">',
										'<table border="0" cellpadding="0" cellspacing="0" width="780">',
											'<tr>',
												'<td width="10"></td>',
												'<td width="65">',
													'<select name="ty" size="1" style="font-family:굴림; font-size:9pt; width:60;">',
													'</select>',
												'</td>',
												'<td width="20" align="left"><span style="font-size:9pt;">년</span></td>',
												'<td width="65">',
													'<select name="tm" size="1" style="font-family:굴림; font-size:9pt; width:60;" onChange="this.form.submit();">',
														'<option value="01">01</option>',
														'<option value="02">02</option>',
														'<option value="03">03</option>',
														'<option value="04">04</option>',
														'<option value="05">05</option>',
														'<option value="06">06</option>',
														'<option value="07">07</option>',
														'<option value="08">08</option>',
														'<option value="09">09</option>',
														'<option value="10">10</option>',
														'<option value="11">11</option>',
														'<option value="12">12</option>',
													'</select>',
												'</td>',
												'<td width="30"><span style="font-size:9pt;">월</span></td>',
												'<td width="65" align="right"><span style="font-size:9pt; letter-spacing:2pt;">원천징수</span></td>',
												'<td width="30"></td>',
												'<td width="340" align="left"></td>',
												'<td width="155" align="right"><input type="button" value=" 인 쇄 " onClick="javascript:PrintAll();"></td>',
											'</tr>',
										'</table>',
									'</form>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="780">',
									'<table border="0" cellspacing="1" width="780" bordercolordark="#F4F4F4" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
										'<tr>',
											'<td width="50" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt;">성명</span></td>',
											'<td width="50" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt;">날짜</span></td>',
											'<td width="100" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt;">주민등록번호</span></td>',
											'<td width="280" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt;">주소</span></td>',
											'<td width="50" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt;">구분</span></td>',
											'<td width="70" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt;">지급액</span></td>',
											'<td width="60" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt;">소득세</span></td>',
											'<td width="60" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt;">주민세</span></td>',
											'<td width="60" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt;">합계</span></td>',
										'</tr>',
										'<tr>',
											'<td width="50" height="25" align="center" bgcolor="#FFFFFF"><span style="font-size:9pt;"><a href="javascript:DelIt();"><?=$mrow[KYNAME]?></a></span></td>',
											'<td width="50" height="25" align="center" bgcolor="#FFFFFF"><span style="font-size:9pt;"><?=substr($mrow[KYDATE1],2,2)?>.<?=substr($mrow[KYDATE1],4,2)?>.<?=$mrow[KYDATE2]?></span></td>',
											'<td width="100" height="25" align="center" bgcolor="#FFFFFF"><span style="font-size:9pt;"><?=$mrow[KYNUM]?></span></td>',
											'<td width="280" height="25" align="left" bgcolor="#FFFFFF"><span style="font-size:9pt; padding-left:3pt;"><?=$addr?></span></td>',
											'<td width="50" height="25" align="center" bgcolor="#FFFFFF"><span style="font-size:9pt; padding-right:0pt;"><?=$gubn?></span></td>',
											'<td width="70" height="25" align="right" bgcolor="#FFFFFF"><span style="font-size:9pt; padding-right:3pt;"><INPUT name="KYANMT" onKeypress="if(event.keyCode == 13){javascript:chAmnt();}" value="" style="text-align:right; font-family:굴림; font-size:9pt; border-width:0px; border-color:rgb(204,204,204); border-style:solid; width:64px;"></span></td>',
											'<td width="60" height="25" align="right" bgcolor="#FFFFFF"><span style="font-size:9pt; padding-right:3pt;"><INPUT name="KYTAX1" onKeypress="if(event.keyCode == 13){javascript:chAmnt();}" value="" style="text-align:right; font-family:굴림; font-size:9pt; border-width:0px; border-color:rgb(204,204,204); border-style:solid; width:54px;"></span></td>',
											'<td width="60" height="25" align="right" bgcolor="#FFFFFF"><span style="font-size:9pt; padding-right:3pt;"><INPUT name="KYTAX2" onKeypress="if(event.keyCode == 13){javascript:chAmnt();}" value="" style="text-align:right; font-family:굴림; font-size:9pt; border-width:0px; border-color:rgb(204,204,204); border-style:solid; width:54px;"></span></td>',
											'<td width="60" height="25" align="right" bgcolor="#FFFFFF"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($mrow[KYTAX1] + $mrow[KYTAX2])?></span></td>',
										'</tr>',
										'<tr>',
											'<td width="50" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt;"><?=$rec_no?></span></td>',
											'<td width="50" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt; padding-left:0pt;"></span></td>',
											'<td width="100" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt; padding-left:0pt;"></span></td>',
											'<td width="280" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt; padding-left:0pt;"></span></td>',
											'<td width="50" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt; padding-left:0pt;"></span></td>',
											'<td width="70" height="25" align="right" bgcolor="#F4F4F4"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($sum_1)?></span></td>',
											'<td width="60" height="25" align="right" bgcolor="#F4F4F4"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($sum_2)?></span></td>',
											'<td width="60" height="25" align="right" bgcolor="#F4F4F4"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($sum_3)?></span></td>',
											'<td width="60" height="25" align="right" bgcolor="#F4F4F4"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($sum_2 + $sum_3)?></span></td>',
										'</tr>',
									'</table>',
								'</td>',
							'</tr>',
						'</table>',
						'<p><br>',
						'<form name="aform" method="post">',
							'<input type="hidden" name="KYDATE1" value="<?=$tdate?>">',
							'<table border="0" cellspacing="1" width="780" bordercolordark="#F4F4F4" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
								'<tr>',
									'<td width="90" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt; letter-spacing:35pt;"><b>날짜</b></span></td>',
									'<td width="300" height="25" align="center" bgcolor="#FFFFFF"><span style="font-size:9pt;"><INPUT name="KYDATE2" style="width:290px; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid;"></span></td>',
									'<td width="90" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt; padding-left:0pt;"></span></td>',
									'<td width="300" height="25" align="center" bgcolor="#FFFFFF"><span style="font-size:9pt; padding-left:0pt;"></span></td>',
								'</tr>',
								'<tr>',
									'<td width="90" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>주민등록번호</b></span></td>',
									'<td width="300" height="25" align="center" bgcolor="#FFFFFF"><span style="font-size:9pt;"><INPUT name="KYNUM" onKeypress="if(event.keyCode == 13){javascript:FindNm();}" style="width:290px; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid;"></span></td>',
									'<td width="90" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt; letter-spacing:35pt;"><b>성명</b></span></td>',
									'<td width="300" height="25" align="center" bgcolor="#FFFFFF"><span style="font-size:9pt;"><INPUT name="KYNAME" style="width:290px; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid;"></span></td>',	        
								'</tr>',
								'<tr>',
									'<td width="90" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt; letter-spacing:35pt;"><b>주소</b></span></td>',
									'<td width="690" colspan="3" height="25" align="center" bgcolor="#FFFFFF"><span style="font-size:9pt;"><INPUT name="KYADDR" style="width:680px; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid;"></span></td>',        
								'</tr>',
								'<tr>',
									'<td width="90" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt; letter-spacing:13pt;"><b>지급액</b></span></td>',
									'<td width="300" height="25" align="center" bgcolor="#FFFFFF"><span style="font-size:9pt;"><INPUT name="KYAMNT" onkeyup="auto_comma(this);" style="width:290px; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid;"></span></td>',
									'<td width="90" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt; padding-left:0pt;"></span></td>',
									'<td width="300" height="25" align="center" bgcolor="#FFFFFF"><span style="font-size:9pt; padding-left:0pt;"></span></td>',
								'</tr>',
								'<tr>',
									'<td width="90" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt; letter-spacing:35pt;"><b>적요</b></span></td>',
									'<td width="690" colspan="3" height="25" align="center" bgcolor="#FFFFFF"><span style="font-size:9pt;"><INPUT name="KYCOMM" style="width:680px; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid;"></span></td>',
								'</tr>',
								'<tr>',
									'<td width="90" height="25" align="center" bgcolor="#F4F4F4"><span style="font-size:9pt; letter-spacing:35pt;"><b>비고</b></span></td>',
									'<td width="690" colspan="3" height="25" align="center" bgcolor="#FFFFFF"><span style="font-size:9pt;"><INPUT name="KYGUBN" style="width:680px; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid;"></span></td>',
								'</tr>',
							'</table>',
							'<p>',
							'<center>',
								'<input type="button" value=" 등 록 " onClick="javascript:chkS();">',
							'</center>',
						'</form>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "3": //도서별 월별집계 -> jejak/su/501.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:150px; margin-left:15px;">',
					'<div style="width:780px; height:130px; padding:10px 0px 10px 0px;">',
						'<form name="frmMain" method="post" action="501.php">',
							'<table border="0" cellpadding="0" cellspacing="0" width="720">',
								'<tr>',
									'<td width="720">',
										'<table border="0" cellpadding="0" cellspacing="0" width="720" height="30">',
											'<tr>',
												'<td width="720" height="30" align="center" valign="middle"><b><span style="font-size:13pt;">도서별 월별 집계</span></b></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720">',
										'<table border="1" cellspacing="0" width="720" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="90" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">작업년도</font></span></td>',
												'<td width="100" height="30" align="center"><p style="margin-left:0px;"><INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:96px;" name="date1" maxlength="2" onKeypress="if(event.keyCode == 13){javascript:chkDate();}"></p></td>',
												'<td width="90" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">도서코드</font></span></td>',
												'<td width="100" height="30" align="center"><p style="margin-left:0px;"><INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:96px;" name="book1" maxlength="6" onKeypress="if(event.keyCode == 13){javascript:chkBook1();}"></p></td>',
												'<td width="340" height="30"><p style="margin-left:10px;"><INPUT style="font-family:굴림; font-size:9pt; border-width:0px; border-color:rgb(204,204,204); border-style:solid; width:320px;" name="book2" onFocus="blur();"></p></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="2" bgcolor="#E0E0E0"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								/* '<tr>',
									'<td width="720">',
										'<table border="1" cellspacing="0" width="720" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="20" rowspan="2" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">월</font></span></td>',
												'<td width="140" colspan="2" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">구매</font></span></td>',        
												'<td width="140" colspan="2" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">판매</font></span></td>',
												'<td width="140" colspan="2" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">반입</font></span></td>',
												'<td width="140" colspan="2" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">증정</font></span></td>',
												'<td width="140" colspan="2" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">폐기</font></span></td>',
											'</tr>',
											'<tr>',
												'<td width="60" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">수량</font></span></td>',        
												'<td width="80" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">금액</font></span></td>',
												'<td width="60" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">수량</font></span></td>',        
												'<td width="80" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">금액</font></span></td>',
												'<td width="60" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">수량</font></span></td>',        
												'<td width="80" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">금액</font></span></td>',
												'<td width="60" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">수량</font></span></td>',        
												'<td width="80" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">금액</font></span></td>',
												'<td width="60" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">수량</font></span></td>',        
												'<td width="80" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">금액</font></span></td>',        
											'</tr>',
											'<tr>',
												'<td width="20" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=$kk?></span></td>',
												'<td width="60" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[sumq1])?></span></td>',
												'<td width="80" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[suma1])?></span></td>',
												'<td width="60" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[sumq3])?></span></td>',
												'<td width="80" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[suma3])?></span></td>',
												'<td width="60" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[sumq4])?></span></td>',
												'<td width="80" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[suma4])?></span></td>',
												'<td width="60" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[sumq5])?></span></td>',
												'<td width="80" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[suma5])?></span></td>',
												'<td width="60" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[sumq6])?></span></td>',
												'<td width="80" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[suma6])?></span></td>',
											'</tr>',
											'<tr>',
												'<td width="20" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;">계</span></td>',
												'<td width="60" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_sumq1)?></span></td>',
												'<td width="80" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_suma1)?></span></td>',
												'<td width="60" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_sumq3)?></span></td>',
												'<td width="80" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_suma3)?></span></td>',
												'<td width="60" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_sumq4)?></span></td>',
												'<td width="80" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_suma4)?></span></td>',
												'<td width="60" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_sumq5)?></span></td>',
												'<td width="80" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_suma5)?></span></td>',
												'<td width="60" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_sumq6)?></span></td>',
												'<td width="80" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_suma6)?></span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"> </td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="2" bgcolor="#E0E0E0"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720"></td>',
								'</tr>', */
							'</table>',
							'<table>',
								'<tr>',
									'<td width="780" height="10"><!-- 여백 --></td>',
								'</tr>',
								'<tr>',
									'<td align="center" height="30"><input type="button" value=" 인쇄 " onClick="javascript:Pr1();"></td>',
								'</tr>',
							'</table>',
						'</form>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "4": //년도별 월별집계 -> jejak/su/504.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:120px; margin-left:15px;">',
					'<div style="width:780px; height:100px; padding:10px 0px 10px 0px;">',
						'<form name="frmMain" method="post" action="504.php">',
							'<table border="0" cellpadding="0" cellspacing="0" width="720">',
								'<tr>',
									'<td width="720">',
										'<table border="0" cellpadding="0" cellspacing="0" width="720" height="30">',
											'<tr>',
												'<td width="720" height="30" align="center" valign="middle"><b><span style="font-size:13pt;">월별 수량 및 금액 집계</span></b></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720">',
										'<table border="1" cellspacing="0" width="720" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="90" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">작업년도</font></span></td>',
												'<td width="100" height="30" align="center"><p style="margin-left:0px;"><INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:96px;" name="date1" maxlength="2" onKeypress="if(event.keyCode == 13){javascript:chkDate();}"></p></td>',
												'<td width="530" align="center" valign="middle" height="30"><span style="font-size:9pt; padding-left:0pt;"></span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="2" bgcolor="#E0E0E0"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								/* '<tr>',
									'<td width="720">',
										'<table border="1" cellspacing="0" width="720" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="20" rowspan="2" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">월</font></span></td>',
												'<td width="140" colspan="2" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">구매</font></span></td>',        
												'<td width="140" colspan="2" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">판매</font></span></td>',
												'<td width="140" colspan="2" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">반입</font></span></td>',
												'<td width="140" colspan="2" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">증정</font></span></td>',
												'<td width="140" colspan="2" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">폐기</font></span></td>',
											'</tr>',
											'<tr>',
												'<td width="60" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">수량</font></span></td>',        
												'<td width="80" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">금액</font></span></td>',
												'<td width="60" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">수량</font></span></td>',        
												'<td width="80" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">금액</font></span></td>',
												'<td width="60" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">수량</font></span></td>',        
												'<td width="80" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">금액</font></span></td>',
												'<td width="60" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">수량</font></span></td>',        
												'<td width="80" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">금액</font></span></td>',
												'<td width="60" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">수량</font></span></td>',        
												'<td width="80" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">금액</font></span></td>',        
											'</tr>',
											'<tr>',
												'<td width="20" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=$kk?></span></td>',
												'<td width="60" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[sumq1])?></span></td>',
												'<td width="80" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[suma1])?></span></td>',
												'<td width="60" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[sumq3])?></span></td>',
												'<td width="80" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[suma3])?></span></td>',
												'<td width="60" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[sumq4])?></span></td>',
												'<td width="80" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[suma4])?></span></td>',
												'<td width="60" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[sumq5])?></span></td>',
												'<td width="80" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[suma5])?></span></td>',
												'<td width="60" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[sumq6])?></span></td>',
												'<td width="80" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($row[suma6])?></span></td>',
											'</tr>',
											'<tr>',
												'<td width="20" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;">계</span></td>',
												'<td width="60" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_sumq1)?></span></td>',
												'<td width="80" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_suma1)?></span></td>',
												'<td width="60" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_sumq3)?></span></td>',
												'<td width="80" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_suma3)?></span></td>',
												'<td width="60" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_sumq4)?></span></td>',
												'<td width="80" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_suma4)?></span></td>',
												'<td width="60" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_sumq5)?></span></td>',
												'<td width="80" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_suma5)?></span></td>',
												'<td width="60" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_sumq6)?></span></td>',
												'<td width="80" bgcolor="#F4F4F4" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($t_suma6)?></span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"> </td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="2" bgcolor="#E0E0E0"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720"></td>',
								'</tr>', */
							'</table>',
						'</form>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "5": //도서별 제작현황 -> jejak/su/503.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:120px; margin-left:15px;">',
					'<div style="width:780px; height:100px; padding:10px 0px 10px 0px;">',
						'<form name="frmAdd" method="post" action="503.php">',
							'<table border="0" cellpadding="0" cellspacing="0" width="720">',
								'<tr>',
									'<td width="720">',
										'<table border="0" cellpadding="0" cellspacing="0" width="720" height="30">',
											'<tr>',
												'<td width="720" height="30" align="center" valign="middle"><b><span style="font-size:13pt;">도서별 제작 현황</span></b></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720">',
										'<table border="1" cellspacing="0" width="720" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="90" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">도서코드</font></span></td>',
												'<td width="100" height="30" align="center"><p style="margin-left:0px;"><INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:96px;" name="man1" maxlength="6" onKeypress="if(event.keyCode == 13){javascript:chkBook1();}"></p></td>',
												'<td width="530" height="30"><p style="margin-left:10px;"><INPUT style="font-family:굴림; font-size:9pt; border-width:0px; border-color:rgb(204,204,204); border-style:solid; width:320px;" name="book2" onFocus="blur();" onClick="javascript:srcBook();"></p></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="2" bgcolor="#E0E0E0"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								/* '<tr>',
									'<td width="720">',
										'<table border="1" cellspacing="0" width="720" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="120" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">제작년월</font></span></td>',        
												'<td width="120" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">부수</font></span></td>',
												'<td width="140" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">제작비</font></span></td>',
												'<td width="120" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">입고수량</font></span></td>',
												'<td width="120" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">미입고수량</font></span></td>',
												'<td width="100" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">증감</font></span></td>',
											'</tr>',
											'<tr style="cursor:hand;" onClick="javascript:View_Com();">',
												'<td width="120" height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=date("y.m.d", $bdate)?></span></td>',
												'<td width="120" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:20pt;"><?=number_format($mrow[bnum])?></span></td>',
												'<td width="140" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:20pt;"><?=number_format($total_cost)?></span></td>',
												'<td width="120" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:20pt;"><?=number_format($total_in)?></span></td>',
												'<td width="120" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:20pt;"></span></td>',
												'<td width="100" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:20pt;"></span></td>',
											'</tr>',
											'<tr style="display:none;" id="comment<?=$ii?>">',
												'<td width="720" colspan="6" align="center" bgcolor="#FCFCFC">',
													'<table border="0" width="200">',    			
														'<tr>',
															'<td width="100"><span style="font-size:9pt;"><?=substr($row[idate],0,2)?>.<?=substr($row[idate],2,2)?>.<?=substr($row[idate],4,2)?></span></td>',
															'<td width="100" align="right"><span style="font-size:9pt; padding-right:20pt;"><?=number_format($row[inum])?> 부</span></td>',
														'</tr>',
													'</table>',
												'</td>',
											'</tr>',
											'<tr>',
												'<td width="120" height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=$mrow[WWYYYY]?>.<?=$mrow[WWMMMM]?>.<?=$mrow[WWDDDD]?></span></td>',
												'<td width="120" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:20pt;"><?=number_format($mrow[WWBUSU])?></span></td>',
												'<td width="140" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:20pt;"><?=number_format($mrow[WTTOTL])?></span></td>',
												'<td width="120" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:20pt;"></span></td>',
												'<td width="120" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:20pt;"></span></td>',
												'<td width="100" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:20pt;"></span></td>',
											'</tr>',		
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"> </td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="2" bgcolor="#E0E0E0"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720"></td>',
								'</tr>', */
							'</table>',
						'</form>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "7": //전기 이월 작업 -> jejak/su/304.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:540px; margin-left:15px;">',
					'<div style="width:780px; height:520px; padding:10px 0px 10px 0px;">',
						'<form name="frmMain">',
							'<table border="0" cellpadding="0" cellspacing="0" width="720" height="500">',
								'<tr>',
									'<td width="720" valign="middle">',
										'<table border="0" cellpadding="0" cellspacing="0" width="720" height="30">',
											'<tr>',
												'<td width="720" height="30" align="center" valign="middle"><b><span style="font-size:13pt;">전기 이월 작업</span></b></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" valign="middle" align="center">',
										'<table border="0" cellspacing="0" width="290" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="90" bgcolor="white" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">기준년도</font></span></td>',
												'<td width="100" height="30" align="center"><p style="margin-left:0px;"><INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:96px;" name="date1" maxlength="2" onKeypress="if(event.keyCode == 13){javascript:chkDate();}"></p></td>',
												'<td width="100" height="30" align="center"><input type="button" value=" 실 행 " onClick="javascript:SendFrm();"></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
							'</table>',
						'</form>',
						'<div id="Lay1" name="Layer1" style="visibility:hidden; position:absolute; width:300pt height:300pt; top:210pt; left:400pt;">',
							'<img src="/resources/style/images/jejak/time_02.gif" width="300" height="300" border="0">',
						'</div>',
						'<div>',
							'<iframe name="tFrm" width="0" height="0"></iframe>',
						'</div>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "9": //미입고 도서 -> jejak/su/502.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:960px; margin-left:15px;">',
					'<div style="width:780px; height:960px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
                            '<tr>',
								'<td width="780" height="10"></td>',
							'</tr>',
							'<tr>',
								'<td width="780">',
									'<form name="frmMain" method="post" action="502.php">',
										'<table border="0" cellpadding="0" cellspacing="0" width="720">',
											'<tr>',
												'<td width="720">',
													'<table border="0" cellpadding="0" cellspacing="0" width="720" height="30">',
														'<tr>',
															'<td width="720" colspan="2" height="30" align="center" valign="middle"><b><span style="font-size:13pt;">미입고 도서현황</span></b></td>',
														'</tr>',
														'<tr>',
															'<td width="300" height="30" align="left" valign="middle"><span style="font-size:9pt; padding-left:10pt;"></span></td>',
															'<td width="420" height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:10pt;">',
																'<input type="button" value="새로 계산" onClick="javascript:MkNew();">&nbsp;&nbsp;&nbsp;&nbsp;',
																'<input type="button" value=" 인쇄 " onClick="javascript:Pr1();"></span>',
															'</td>',
														'</tr>',
													'</table>',
												'</td>',
											'</tr>',
											'<tr>',
												'<td width="720" height="10"></td>',
											'</tr>',    
										'</table>',
									'</form>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="720" height="2" bgcolor="#E0E0E0"></td>',
							'</tr>',
							'<tr>',
								'<td width="720" height="10"></td>',
							'</tr>',
							'<tr>',
								'<td width="720">',
									'<table border="1" cellspacing="0" width="720" bordercolordark="white" bordercolorlight="#CCCCCC">',
										'<tr>',
											'<td width="40" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">번호</font></span></td>',
											'<td width="60" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">제작일</font></span></td>',
											'<td width="60" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">도서코드</font></span></td>',
											'<td width="350" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">도서명</font></span></td>',
											'<td width="60" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">제작부수</font></span></td>',
											'<td width="80" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">미입고수량</font></span></td>',
											'<td width="70" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">제본소</font></span></td>',
										'</tr>',
										'<tr>',
											'<td width="40" bgcolor="#FFFFFF" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666"><?=$ii?></font></span></td>',
											'<td width="60" bgcolor="#FFFFFF" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666"><?=substr($mrow[MKDATE], 2, 2)?>.<?=substr($mrow[MKDATE], 4, 2)?>.<?=substr($mrow[MKDATE], 6, 2)?></font></span></td>',
											'<td width="60" bgcolor="#FFFFFF" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666"><?=$mrow[MKBOOK]?></font></span></td>',
											'<td width="350" bgcolor="#FFFFFF" align="left" valign="middle" height="30"><span style="font-size:9pt; padding-left:10;"><font color="#666666"><?=$mrow[MKNAME]?></font></span></td>',
											'<td width="60" bgcolor="#FFFFFF" align="right" valign="middle" height="30"><span style="font-size:9pt; padding-right:10;"><font color="#666666"><?=number_format($mrow[MKNUM])?></font></span></td>',
											'<td width="80" bgcolor="#FFFFFF" align="right" valign="middle" height="30"><span style="font-size:9pt; padding-right:10;"><font color="#666666"><?=number_format($mrow[MKNUM2])?></font></span></td>',
											'<td width="70" bgcolor="#FFFFFF" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666"><?=$mrow[MKNAME2]?></font></span></td>',
										'</tr>',
									'</table>',
								'</td>',
							'</tr>',
							'<tr>',
								'<td width="720" height="10"> </td>',
							'</tr>',
							'<tr>',
								'<td width="720"></td>',
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "11": //전도서재고조회 -> jejak/su/505.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:120px; margin-left:15px;">',
					'<div style="width:780px; height:100px; padding:10px 0px 10px 0px;">',
						'<form name="frmAdd" method="post" action="505.php">',
							'<table border="0" cellpadding="0" cellspacing="0" width="720">',
								'<tr>',
									'<td width="720">',
										'<table border="0" cellpadding="0" cellspacing="0" width="720" height="30">',
											'<tr>',
												'<td width="720" height="30" align="center" valign="middle"><b><span style="font-size:13pt;">도서 재고 현황</span></b></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720">',
										'<table border="1" cellspacing="0" width="720" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="90" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">수량</font></span></td>',
												'<td width="100" height="30" align="center"><p style="margin-left:0px;"><INPUT style="text-align:center; font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:96px;" name="wnum" onKeypress="if(event.keyCode == 13){javascript:chkBook1();}"></p></td>',
												'<td width="530" height="30">&nbsp;</td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="2" bgcolor="#E0E0E0"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								/* '<tr>',
									'<td width="720">',
										'<table border="1" cellspacing="0" width="720" bordercolordark="white" bordercolorlight="#CCCCCC">',
											'<tr>',
												'<td width="30" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">번호</font></span></td>',
												'<td width="50" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">도서코드</font></span></td>',
												'<td width="240" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">도서명</font></span></td>',
												'<td width="100" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">출판사재고</font></span></td>',
												'<td width="100" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">아트재고</font></span></td>',        
												'<td width="100" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">합계</font></span></td>',
												'<td width="100" bgcolor="#F4F4F4" align="center" valign="middle" height="30"><span style="font-size:9pt;"><font color="#666666">미입고</font></span></td>',
											'</tr>',
											'<tr>',
												'<td height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=$ii?></span></td>',
												'<td height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=$mrow[0]?></span></td>',
												'<td height="30" align="left" valign="middle"><span style="font-size:9pt; padding-left:2pt;"><?=$mrow[1]?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($num1)?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($num2)?></span></td>',        
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($sum)?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?if ($num3) {?><font color="red"><?=number_format($num3)?></font><?}?></span></td>',
											'</tr>',
											'<tr bgcolor="CCFFCC">',
												'<td height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=$ii?></span></td>',
												'<td height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=$mrow[0]?></span></td>',
												'<td height="30" align="left" valign="middle"><span style="font-size:9pt; padding-left:2pt;"><?=$mrow[1]?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($num1)?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($num2)?></span></td>',        
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($sum)?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?if ($num3) {?><font color="red"><?=number_format($num3)?></font><?}?></span></td>',
											'</tr>',
											'<tr>',
												'<td height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=$ii?></span></td>',
												'<td height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=$mrow[0]?></span></td>',
												'<td height="30" align="left" valign="middle"><span style="font-size:9pt; padding-left:2pt;"><?=$mrow[1]?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($num1)?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($num2)?></span></td>',        
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($sum)?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?if ($num3) {?><font color="red"><?=number_format($num3)?></font><?}?></span></td>',
											'</tr>',
											'<tr bgcolor="CCFFCC">',
												'<td height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=$ii?></span></td>',
												'<td height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=$mrow[0]?></span></td>',
												'<td height="30" align="left" valign="middle"><span style="font-size:9pt; padding-left:2pt;"><?=$mrow[1]?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($num1)?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($num2)?></span></td>',        
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($sum)?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?if ($num3) {?><font color="red"><?=number_format($num3)?></font><?}?></span></td>',
											'</tr>',
											'<tr>',
												'<td height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=$ii?></span></td>',
												'<td height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=$mrow[0]?></span></td>',
												'<td height="30" align="left" valign="middle"><span style="font-size:9pt; padding-left:2pt;"><?=$mrow[1]?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($num1)?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($num2)?></span></td>',        
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($sum)?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?if ($num3) {?><font color="red"><?=number_format($num3)?></font><?}?></span></td>',
											'</tr>',
											'<tr bgcolor="CCFFCC">',
												'<td height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=$ii?></span></td>',
												'<td height="30" align="center" valign="middle"><span style="font-size:9pt; padding-right:0pt;"><?=$mrow[0]?></span></td>',
												'<td height="30" align="left" valign="middle"><span style="font-size:9pt; padding-left:2pt;"><?=$mrow[1]?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($num1)?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($num2)?></span></td>',        
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?=number_format($sum)?></span></td>',
												'<td height="30" align="right" valign="middle"><span style="font-size:9pt; padding-right:3pt;"><?if ($num3) {?><font color="red"><?=number_format($num3)?></font><?}?></span></td>',
											'</tr>',
										'</table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"> </td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="2" bgcolor="#E0E0E0"></td>',
								'</tr>',
								'<tr>',
									'<td width="720" height="10"></td>',
								'</tr>',
								'<tr>',
									'<td width="720"></td>',
								'</tr>', */
							'</table>',
						'</form>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
		default:
			break;
	}
}