function jmenu6(val) { //직접경비
	switch (val) {
		case "1": //선불직접경비 입력 -> jejak/kb/sun.php
			return [
			
			].join('');
			
		case "3": //용지대 -> jejak/kb/exl_10.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:123px; margin-left:15px;">',
					'<div style="width:780px; height:103px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="exl_10.php">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',
										'<select name="ty" size="1" onChange="javascript:ChangeDate(17);">',
										'</select> 년&nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(17);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월&nbsp;용지대 관리 리스트</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table id="kbYongjiData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"><table>',
									'</td>',
								'</tr>',
						'</table>',	
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "3_인쇄팝업": 
			return [
			'<div style="width:780px;">',
				'<table id="popdata" width="750" border="0" cellpading="0" cellspacing="0"></table>',
				'<br>',
				'<table id="popdata2" width="750" border="0" cellpading="0" cellspacing="0"></table>',
			'</div>'
			].join('');

		case "4": //출력료 -> jejak/kb/exl_4.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:4401px; margin-left:15px;">',
					'<div style="width:780px; height:4381px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40"><span style="font-size:12pt;"><b>- &nbsp;출력료 관리 리스트</b></span></td>',
							'</tr>',					
							'<tr>',
								'<td width="780">',
									'<table id="kbPrintData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
								'</td>',
							'</tr>',
						'</table>',					
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "5": //사보료 -> jejak/kb/exl_3.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:6075px; margin-left:15px;">',
					'<div style="width:780px; height:6055px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<tr>',
								'<td width="780" height="40"><span style="font-size:12pt;"><b>- &nbsp;사보료 관리 리스트</b></span></td>',
							'</tr>',
							'<tr>',
								'<td width="780">',
									'<table id="kbHouseOrganData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>', 
								'</td>',
							'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "6": //인쇄비 -> jejak/kb/ex_6.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:102px; margin-left:15px;">',
					'<div style="width:780px; height:82px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="ex_6.php">',
								'<tr>',
									'<td width="391" height="40"><p><span style="font-size:9pt;"><b>-&nbsp;',
										'<select name="ty" size="1" onChange="javascript:ChangeDate(18);">',
										'</select>년&nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(18);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>월&nbsp;인쇄비 관리 리스트</b></span></p>',
									'</td>',
									'<td width="391" height="40" align="right" valign="middle">',
										'<input type="button" value="거래명세 출력" onClick="javascript:PrintPresswork();">&nbsp;&nbsp;',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table id="kbPressworkDataTemp" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="60" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">제작번호</span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">년월일</span></td>',
												'<td width="280" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
												'<td width="77" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">거래처</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">인쇄비</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">필름.소부비</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">계산</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">회계</span></td>',
											'</tr>',
										'</table>',
										'<table id="kbPressworkData" style="display:none;" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td colspan="2" height="10" width="780"></td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "인쇄비_디테일":
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:1890px; margin-left:15px;">',
					'<div style="width:780px; height:1870px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
						    '<tr>',
						        '<td width="780" height="40"><span style="font-size:9pt;"><b>- &nbsp;인쇄비 관리</b></span></td>',
						    '</tr>',
						'</table>',
						'<table id="kbPressworkDetailData" border="0" cellpadding="0" cellspacing="0" width="780"></table>',   
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',   
						    '<tr>',
						        '<td width="780" height="10"></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780">',
						            '<table border="0" cellpadding="0" cellspacing="0" width="780">',
						                '<tr>',
						                    '<td width="780" height="30"><span style="font-size:9pt;">- 필름대</span></td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="780">',
						                        '<table id="kbPressworkDetailData2" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
						                    '</td>',
						                '</tr>',
						            '</table>',
						        '</td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780" height="10"></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780">',
						        	'<table border="0" cellpadding="0" cellspacing="0" width="780">',
						                '<tr>',
						                    '<td width="780" height="30"><span style="font-size:9pt;">- 소부비</span></td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="780">',
						                        '<table id="kbPressworkDetailData3" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
						                    '</td>',
						                '</tr>',
						            '</table>',
						        '</td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780" height="10"></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780">',
						        	'<table border="0" cellpadding="0" cellspacing="0" width="780">',
						                '<tr>',
						                    '<td width="780" height="30"><span style="font-size:9pt;">- 인쇄비</span></td>',
						                '</tr>',
						                '<tr>',
						                    '<td width="780">',
						                        '<table id="kbPressworkDetailData4" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
						                    '</td>',
						                '</tr>',
						            '</table>',
						        '</td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780" height="10"></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780">',
						            '<table border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
						                '<tr>',
						                    '<td width="129" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>합계</b></span></td>',
						                    '<td style="padding-left:10;" width="648" bgcolor="white" height="30"><span style="font-size:9pt;"><a id="sum_all"></a></span></td>',
						                '</tr>',
						            '</table>',
						        '</td>',
						    '</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "6_인쇄팝업": 
			return [
			'<div style="width:780px;">',
				'<div id="popdata" width="700px" border="0" cellpading="0" cellspacing="0"></div>',
				'<div id="popdata2" width="700px" border="0" cellpading="0" cellspacing="0"></div>',
			'</div>'
		].join('');

		case "7": //제본비 -> jejak/kb/ex_7_1.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:1890px; margin-left:15px;">',
					'<div style="width:780px; height:1870px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="ex_7_1.php">',
								'<tr>',
									'<td width="391" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',
										'<select name="ty" size="1" onChange="javascript:ChangeDate(19);">',
										'</select>년&nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(19);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>월 제본비 관리 리스트</b></span></p>',
									'</td>',
									'<td width="391" height="40" align="right" valign="middle">',
										'<input type="button" value=" 거래명세 출력 " onClick="javascript:PrintBinding();">',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table id="kbBindingData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "7_인쇄팝업": 
			return [
			'<div style="width:750px;">',
				'<div id="popdata" width="750" border="0" cellpading="0" cellspacing="0"></table>',
			'</div>'
		].join('');

		case "8": //코팅비 -> jejak/kb/ex_8_1.php
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:133px; margin-left:15px;">',
					'<div style="width:780px; height:113px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="ex_8_1.php">',
								'<tr>',
									'<td width="391" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',
										'<select name="ty" size="1" onChange="javascript:ChangeDate(20);">',
										'</select>년&nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(20);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select>월&nbsp;',
										'<select name="td" size="1" style="font-family:굴림; font-size:9pt;  width:60;" onChange="javascript:ChangeDate(21);">',
										'</select>일&nbsp;코팅비 관리 리스트</b></span></p>',
									'</td>',
									'<td width="391" height="40" align="right" valign="middle">',
										'<input type="button" value=" 거래명세 출력 " onClick="javascript:PrintKbCoating();">',
									'</td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780" colspan="2">',
										'<table id="kbCoatingDataTemp" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="60" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;">제작번호</span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">년월</span></td>',
												'<td width="260" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">도서명</span></td>',
												'<td width="77" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">수량</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">단가</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">공급가액</span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">거래처</span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;">회계</span></td>',
											'</tr>',
											'<tr>',
												'<td width="547" height="30" colspan="5" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">합계</span></td>',
												'<td width="70" height="30" align="right" valign="middle" bgcolor="white"><span style="font-size:9pt; padding-right:5pt;"></span></td>',
												'<td width="160" height="30" colspan="2" align="center" valign="middle" bgcolor="white"><span style="font-size:9pt;">&nbsp;</span></td>',
											'</tr>',
										'</table>',
										'<table id="kbCoatingData" style="display:none;" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
								'<tr>',
									'<td colspan="2" height="10" width="780"></td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "8_인쇄팝업": 
			return [
			'<div style="width:750px;">',
				'<div id="popdata" width="750" border="0" cellpading="0" cellspacing="0"></table>',
			'</div>'
		].join('');
			
		case "관리비_디테일": 
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
						    '<tr>',
						       '<td width="780" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;<a id="tag_name"></a></b></span></p></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780">',
						        	'<table id="kbManagementDetailData1" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
								'</td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780" height="10"></td>',
						    '</tr>',
						    '<tr>',
						        '<td width="780">',
						            '<table id="kbManagementDetailData" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
						        '</td>',
						    '</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
			
		case "사보검색": 
			return [
			'<div style="width:780px;">',
				'<table border="0" cellpadding="0" cellspacing="0" width="500" bgcolor="#F6F5F5">',
				    '<tr>',
				        '<td width="500" height="30"></td>',
				    '</tr>',
				    '<tr>',
				        '<td width="500" height="30" align="left" valign="top"><p style="margin-left:50px;"><span style="font-size:9pt;"><b>- 거래처 검색</b></span></p></td>',
				    '</tr>',
				    '<tr>',
				        '<td width="600" align="center" valign="top">',
				            '<table cellpadding="0" cellspacing="0" width="400">',
				                '<tr>',
				                    '<td width="100" height="30">',
				                        '<select id="key" size="1" style="font-family:돋움; font-size:9pt; width:95px;">',
				                            '<option value="wcname">거래처명</option>',
				                            '<option value="wccode">거래처코드</option>',
				                            '<option value="wcjob">작업분류</option>',
				                        '</select>',
				                    '</td>',
				                    '<td width="230" height="30"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:230px; height:20px; ime-mode:active" id="keyfield"></td>',
				                    '<td width="70" height="30"><input type ="image" id="btnSearch" src="/resources/style/images/jejak/btn_pop_search.gif" width="60" height="20" border="0"></td>',
				                '</tr>',
				            '</table>',
				        '</td>',
				    '</tr>',
				    '<tr>',
				        '<td width="600" height="10"></td>',
				    '</tr>',
				    '<tr>',
				        '<td width="600" height="10"></td>',
				    '</tr>',
				    '<tr>',
				        '<td width="600" align="center" valign="top">',
				            '<table id="popdata" cellpadding="0" cellspacing="1" width="400" align="center" bgcolor="#CCCCCC"></table>',
				        '</td>',
				    '</tr>',
				    '<tr>',
				        '<td width="600" height="10"></td>',
				    '</tr>',
				    '<tr>',
				        '<td width="600" height="30"></td>',
				    '</tr>',
				'</table>',
			'</div>'
		].join('');
			
		case "도서검색": 
			return [
			'<div style="width:780px;">',
				'<table border="0" cellpadding="0" cellspacing="0" width="500" bgcolor="#F6F5F5">'+
				    '<tr>'+
				        '<td width="500" height="30"></td>'+
				    '</tr>'+
				    '<tr>'+
				        '<td width="500" height="30" align="left" valign="top"><p style="margin-left:50px;"><span style="font-size:9pt;"><b>- 도서 검색</b></span></p></td>'+
				    '</tr>'+
				    '<tr>'+
				        '<td width="600" align="center" valign="top">'+
				            '<table cellpadding="0" cellspacing="0" width="400">'+
				                '<tr>'+
				                    '<td width="100" height="30">'+
				                        '<select id="key" size="1" style="font-family:돋움; font-size:9pt; width:95px;">'+
				                            '<option value="sbname2">도서명</option>'+
				                            '<option value="sbbook">도서코드</option>'+
				                        '</select>'+
				                    '</td>'+
				                    '<td width="230" height="30"><INPUT style="font-family:굴림; font-size:9pt; border-width:1px; border-color:rgb(204,204,204); border-style:solid; width:230px; height:20px; ime-mode:active" id="keyfield"></td>'+
				                    '<td width="70" height="30"><input type ="image" id="btnSearch" src="/resources/style/images/jejak/btn_pop_search.gif" width="60" height="20" border="0"></td>'+
				                '</tr>'+
				            '</table>'+
				        '</td>'+
				    '</tr>'+
				    '<tr>'+
				        '<td width="600" height="10"></td>'+
				    '</tr>'+
				    '<tr>'+
				        '<td width="600" height="10"></td>'+
				    '</tr>'+
				    '<tr>'+
				        '<td width="600" align="center" valign="top">'+
				            '<table id="popdataTemp" cellpadding="0" cellspacing="1" width="400" align="center" bgcolor="#CCCCCC">'+
				                '<tr>'+
				                    '<td width="100" height="30" align="center" valign="middle" bgcolor="#E5E5E5"><span style="font-size:9pt;"><b><font color="#333333">코드</font></b></span></td>'+
				                    '<td width="200" bgcolor="#E5E5E5" height="30" align="center" valign="middle"><p><span style="font-size:9pt;"><b><font color="#333333">도서명</font></b></span></p></td>'+
				                    '<td width="96" height="30" bgcolor="#E5E5E5" align="center" valign="middle"><span style="font-size:9pt;"><b><font color="#333333">선택</font></b></span></td>'+
				                '</tr>'+
				            '</table>'+
				            '<table id="popdata" style="display:none;" cellpadding="0" cellspacing="1" width="400" align="center" bgcolor="#CCCCCC"></table>',
				        '</td>'+
				    '</tr>'+
				    '<tr>'+
				        '<td width="600" height="10"></td>'+
				    '</tr>'+
				    '<tr>'+
				        '<td width="600" height="30"></td>'+
				    '</tr>'+
				'</table>'+
			'</div>'
		].join('');

		case "9": //비닐비 -> jejak/kb/exl_9.php?tag=1
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="exl_9.php">',
								'<input type="hidden" name="tag" value="<?=$tag?>">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',							
										'<select name="ty" size="1" onChange="javascript:ChangeDate(22);">',	
										'</select> 년 &nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(22);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;비닐비 관리 리스트</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table id="kbManagementDataTemp" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="90" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>년월일</b></span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서명</b></span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서코드</b></span></td>',
												'<td width="150" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>거래처</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>수량</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>단가</b></span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>금액</b></span></td>',
											'</tr>',
										'</table>',
										'<table id="kbManagementData" style="display:none;" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "10": //케이스대 -> jejak/kb/exl_9.php?tag=2
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="exl_9.php">',
								'<input type="hidden" name="tag" value="<?=$tag?>">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',							
										'<select name="ty" size="1" onChange="javascript:ChangeDate(23);">',
										'</select> 년 &nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(23);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;케이스대 관리 리스트</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table id="kbManagementDataTemp" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="90" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>년월일</b></span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서명</b></span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서코드</b></span></td>',
												'<td width="150" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>거래처</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>수량</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>단가</b></span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>금액</b></span></td>',
											'</tr>',
										'</table>',
										'<table id="kbManagementData" style="display:none;" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "11": //CD음반대 -> jejak/kb/exl_9.php?tag=3
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="exl_9.php">',
								'<input type="hidden" name="tag" value="<?=$tag?>">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',							
										'<select name="ty" size="1" onChange="javascript:ChangeDate(24);">',	
										'</select> 년 &nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(24);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;CD음반대 관리 리스트</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table id="kbManagementDataTemp" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="90" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>년월일</b></span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서명</b></span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서코드</b></span></td>',
												'<td width="150" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>거래처</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>수량</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>단가</b></span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>금액</b></span></td>',
											'</tr>',
										'</table>',
										'<table id="kbManagementData" style="display:none;" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "12": //스티커대 -> jejak/kb/exl_9.php?tag=4
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="exl_9.php">',
								'<input type="hidden" name="tag" value="<?=$tag?>">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',							
										'<select name="ty" size="1" onChange="javascript:ChangeDate(25);">',
										'</select> 년 &nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(25);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;스티커대 관리 리스트</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table id="kbManagementDataTemp" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="90" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>년월일</b></span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서명</b></span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서코드</b></span></td>',
												'<td width="150" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>거래처</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>수량</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>단가</b></span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>금액</b></span></td>',
											'</tr>',
										'</table>',
										'<table id="kbManagementData" style="display:none;" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');

		case "13": //기타 -> jejak/kb/exl_9.php?tag=5
			return [
			'<div style="width:810px; height:815px;">',
				'<div style="width:780px; height:92px; margin-left:15px;">',
					'<div style="width:780px; height:72px; padding:10px 0px 10px 0px;">',
						'<table border="0" cellpadding="0" cellspacing="0" width="780">',
							'<form name="dform" method="post" action="exl_9.php">',
								'<input type="hidden" name="tag" value="<?=$tag?>">',
								'<tr>',
									'<td width="390" height="40"><p><span style="font-size:9pt;"><b>- &nbsp;',							
										'<select name="ty" size="1" onChange="javascript:ChangeDate(26);">',
										'</select> 년 &nbsp;',
										'<select name="tm" size="1" onChange="javascript:ChangeDate(26);">',
											'<option value="01">01</option>',
											'<option value="02">02</option>',
											'<option value="03">03</option>',
											'<option value="04">04</option>',
											'<option value="05">05</option>',
											'<option value="06">06</option>',
											'<option value="07">07</option>',
											'<option value="08">08</option>',
											'<option value="09">09</option>',
											'<option value="10">10</option>',
											'<option value="11">11</option>',
											'<option value="12">12</option>',
										'</select> 월 &nbsp;기타 관리 리스트</b></span></p>',
									'</td>',
									'<td width="390" height="40" align="right" valign="middle"></td>',
								'</tr>',
							'</form>',
								'<tr>',
									'<td width="780">',
										'<table id="kbManagementDataTemp" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC">',
											'<tr>',
												'<td width="90" align="center" valign="middle" bgcolor="#F4F4F4" height="30"><span style="font-size:9pt;"><b>년월일</b></span></td>',
												'<td width="220" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서명</b></span></td>',
												'<td width="70" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>도서코드</b></span></td>',
												'<td width="150" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>거래처</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>수량</b></span></td>',
												'<td width="80" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>단가</b></span></td>',
												'<td width="90" height="30" align="center" valign="middle" bgcolor="#F4F4F4"><span style="font-size:9pt;"><b>금액</b></span></td>',
											'</tr>',
										'</table>',
										'<table id="kbManagementData" style="display:none;" border="0" cellspacing="1" width="780" bordercolordark="white" bordercolorlight="black" bordercolor="#CCCCCC" cellpadding="0" bgcolor="#CCCCCC"></table>',
										'<p><center><a href="javascript:SelKbManagementDetail(0,5);"><img src="/resources/style/images/jejak/b_in.gif" border="0"></a></center></p>',
									'</td>',
								'</tr>',
						'</table>',
					'</div>',
				'</div>',
			'</div>',
			].join('');
		default:
			break;
	}
}